using ShineEngine;

/// <summary>
/// UI实例类型(generated by shine)
/// </summary>
public class HUIInstanceType
{
	public const int Main=1;
	
	public const int Fight=2;
	
	public const int Login=3;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=0;
	
}
