using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GCodeCheckRecord
{
	/// <summary>
	/// 配置文件代码版本校验值
	/// </summary>
	public const string configMD5="5ef98bcc7b10701ab190a0be1b5392b8";
	
	/// <summary>
	/// 配置文件代码数据结构版本号
	/// </summary>
	public const int configVersion=49825488;
	
}
