using AppDomain = ILRuntime.Runtime.Enviorment.AppDomain;
using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class GILRuntimeControl:CILRuntimeControl
{
	/// <summary>
	/// 初始化数据适配器
	/// </summary>
	protected override void initDataAdapters(AppDomain appdomain)
	{
		base.initDataAdapters(appdomain);
	}
	
	protected override void initOtherAdapters(AppDomain appdomain)
	{
		base.initOtherAdapters(appdomain);
		
	}
	
	/// <summary>
	/// 初始化数据适配器
	/// </summary>
	protected override void initGenerateAdapters(AppDomain appdomain)
	{
		base.initGenerateAdapters(appdomain);
		
	}
	
	/// <summary>
	/// 初始化配置适配器
	/// </summary>
	protected override void initConfigAdapters(AppDomain appdomain)
	{
		base.initConfigAdapters(appdomain);
	}
	
	protected override void initDelegate(AppDomain appdomain)
	{
		base.initDelegate(appdomain);

		appdomain.DelegateManager.RegisterMethodDelegate<GCharacterUseData>();
	}
	
}
