using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class HCenterRequestBindTool:MessageBindTool
{
	public HCenterRequestBindTool()
	{
		offSet=HCenterRequestType.off;
		list=new int[HCenterRequestType.count-offSet][];
	}
	
}
