using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class HCenterResponseMaker:DataMaker
{
	public HCenterResponseMaker()
	{
		offSet=HCenterResponseType.off;
		list=new Func<BaseData>[HCenterResponseType.count-offSet];
	}
	
}
