using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class HCenterRequestMaker:DataMaker
{
	public HCenterRequestMaker()
	{
		offSet=HCenterRequestType.off;
		list=new Func<BaseData>[HCenterRequestType.count-offSet];
	}
	
}
