using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class HGameResponseMaker:DataMaker
{
	public HGameResponseMaker()
	{
		offSet=HGameResponseType.off;
		list=new Func<BaseData>[HGameResponseType.count-offSet];
	}
	
}
