using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class HGameRequestMaker:DataMaker
{
	public HGameRequestMaker()
	{
		offSet=HGameRequestType.off;
		list=new Func<BaseData>[HGameRequestType.count-offSet];
	}
	
}
