using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class HGameRequestBindTool:MessageBindTool
{
	public HGameRequestBindTool()
	{
		offSet=HGameRequestType.off;
		list=new int[HGameRequestType.count-offSet][];
	}
	
}
