using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class HotfixDataMaker:DataMaker
{
	public HotfixDataMaker()
	{
		offSet=HotfixDataType.off;
		list=new Func<BaseData>[HotfixDataType.count-offSet];
	}
	
}
