using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class HPlayerPartDataMaker:DataMaker
{
	public HPlayerPartDataMaker()
	{
		offSet=HPlayerPartDataType.off;
		list=new Func<BaseData>[HPlayerPartDataType.count-offSet];
	}
	
}
