using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class HSceneBaseRequestMaker:DataMaker
{
	public HSceneBaseRequestMaker()
	{
		offSet=HSceneBaseRequestType.off;
		list=new Func<BaseData>[HSceneBaseRequestType.count-offSet];
	}
	
}
