using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class HSceneBaseRequestBindTool:MessageBindTool
{
	public HSceneBaseRequestBindTool()
	{
		offSet=HSceneBaseRequestType.off;
		list=new int[HSceneBaseRequestType.count-offSet][];
	}
	
}
