using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class HSceneRequestBindTool:MessageBindTool
{
	public HSceneRequestBindTool()
	{
		offSet=HSceneRequestType.off;
		list=new int[HSceneRequestType.count-offSet][];
	}
	
}
