using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class HSceneBaseResponseMaker:DataMaker
{
	public HSceneBaseResponseMaker()
	{
		offSet=HSceneBaseResponseType.off;
		list=new Func<BaseData>[HSceneBaseResponseType.count-offSet];
	}
	
}
