using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class HSceneResponseMaker:DataMaker
{
	public HSceneResponseMaker()
	{
		offSet=HSceneResponseType.off;
		list=new Func<BaseData>[HSceneResponseType.count-offSet];
	}
	
}
