package com.home.client.part.player;
import com.home.base.part.player.clientData.GBagClientPartData;
import com.home.base.part.player.clientData.GCharacterClientPartData;
import com.home.base.part.player.clientData.GFriendClientPartData;
import com.home.base.part.player.clientData.GFuncClientPartData;
import com.home.base.part.player.clientData.GRoleClientPartData;
import com.home.base.part.player.clientData.GSceneClientPartData;
import com.home.base.part.player.clientData.GTeamClientPartData;
import com.home.base.part.player.clientData.GUnionClientPartData;
import com.home.base.part.player.list.GPlayerClientListData;
import com.home.client.part.player.part.GBagPart;
import com.home.client.part.player.part.GCharacterPart;
import com.home.client.part.player.part.GFriendPart;
import com.home.client.part.player.part.GFuncPart;
import com.home.client.part.player.part.GRolePart;
import com.home.client.part.player.part.GScenePart;
import com.home.client.part.player.part.GTeamPart;
import com.home.client.part.player.part.GUnionPart;
import com.home.commonBase.part.player.clientData.ActivityClientPartData;
import com.home.commonBase.part.player.clientData.GuideClientPartData;
import com.home.commonBase.part.player.clientData.MailClientPartData;
import com.home.commonBase.part.player.clientData.PetClientPartData;
import com.home.commonBase.part.player.clientData.QuestClientPartData;
import com.home.commonBase.part.player.clientData.SceneClientPartData;
import com.home.commonBase.part.player.clientData.SocialClientPartData;
import com.home.commonBase.part.player.clientData.SystemClientPartData;
import com.home.commonBase.part.player.list.PlayerClientListData;
import com.home.commonClient.part.player.Player;
import com.home.commonClient.part.player.base.PlayerBasePart;
import com.home.commonClient.part.player.part.ActivityPart;
import com.home.commonClient.part.player.part.GuidePart;
import com.home.commonClient.part.player.part.MailPart;
import com.home.commonClient.part.player.part.PetPart;
import com.home.commonClient.part.player.part.QuestPart;
import com.home.commonClient.part.player.part.ScenePart;
import com.home.commonClient.part.player.part.SocialPart;
import com.home.commonClient.part.player.part.SystemPart;

/** 玩家数据主体(generated by shine) */
public class GPlayer extends Player
{
	/** 角色 */
	public GCharacterPart gcharacter;
	
	/** 角色 */
	public GRolePart grole;
	
	/** 背包 */
	public GBagPart gbag;
	
	/** 工会 */
	public GUnionPart gunion;
	
	/** 功能 */
	public GFuncPart gfunc;
	
	/** 好友 */
	public GFriendPart gfriend;
	
	/** 组队 */
	public GTeamPart gteam;
	
	/** 场景 */
	public GScenePart gscene;
	
	/** 注册部件 */
	@Override
	protected void registParts()
	{
		_list=new PlayerBasePart[14];
		int i=0;
		
		system=new SystemPart();
		system.setMe(this);
		_list[i++]=system;
		
		gfunc=new GFuncPart();
		func=gfunc;
		gfunc.setMe(this);
		_list[i++]=gfunc;
		
		activity=new ActivityPart();
		activity.setMe(this);
		_list[i++]=activity;
		
		grole=new GRolePart();
		role=grole;
		grole.setMe(this);
		_list[i++]=grole;
		
		gscene=new GScenePart();
		scene=gscene;
		gscene.setMe(this);
		_list[i++]=gscene;
		
		gcharacter=new GCharacterPart();
		character=gcharacter;
		gcharacter.setMe(this);
		_list[i++]=gcharacter;
		
		social=new SocialPart();
		social.setMe(this);
		_list[i++]=social;
		
		gbag=new GBagPart();
		bag=gbag;
		gbag.setMe(this);
		_list[i++]=gbag;
		
		mail=new MailPart();
		mail.setMe(this);
		_list[i++]=mail;
		
		quest=new QuestPart();
		quest.setMe(this);
		_list[i++]=quest;
		
		guide=new GuidePart();
		guide.setMe(this);
		_list[i++]=guide;
		
		gfriend=new GFriendPart();
		friend=gfriend;
		gfriend.setMe(this);
		_list[i++]=gfriend;
		
		gunion=new GUnionPart();
		union=gunion;
		gunion.setMe(this);
		_list[i++]=gunion;
		
		gteam=new GTeamPart();
		team=gteam;
		gteam.setMe(this);
		_list[i++]=gteam;
		
	}
	
	/** 创建列表数据 */
	@Override
	public PlayerClientListData createListData()
	{
		return new GPlayerClientListData();
	}
	
	/** 从列表数据读取 */
	@Override
	public void readListData(PlayerClientListData listData)
	{
		GPlayerClientListData mData=(GPlayerClientListData)listData;
		
		this.system.setData(mData.system);
		this.gfunc.setData(mData.gfunc);
		this.activity.setData(mData.activity);
		this.grole.setData(mData.grole);
		this.gscene.setData(mData.gscene);
		this.gcharacter.setData(mData.gcharacter);
		this.social.setData(mData.social);
		this.gbag.setData(mData.gbag);
		this.mail.setData(mData.mail);
		this.quest.setData(mData.quest);
		this.guide.setData(mData.guide);
		this.gfriend.setData(mData.gfriend);
		this.gunion.setData(mData.gunion);
		this.gteam.setData(mData.gteam);
	}
	
	/** 写列表数据(深拷) */
	@Override
	public void writeListData(PlayerClientListData listData)
	{
		GPlayerClientListData mData=(GPlayerClientListData)listData;
		
		mData.system=(SystemClientPartData)this.system.makePartData();
		mData.gfunc=(GFuncClientPartData)this.gfunc.makePartData();
		mData.activity=(ActivityClientPartData)this.activity.makePartData();
		mData.grole=(GRoleClientPartData)this.grole.makePartData();
		mData.gscene=(GSceneClientPartData)this.gscene.makePartData();
		mData.gcharacter=(GCharacterClientPartData)this.gcharacter.makePartData();
		mData.social=(SocialClientPartData)this.social.makePartData();
		mData.gbag=(GBagClientPartData)this.gbag.makePartData();
		mData.mail=(MailClientPartData)this.mail.makePartData();
		mData.quest=(QuestClientPartData)this.quest.makePartData();
		mData.guide=(GuideClientPartData)this.guide.makePartData();
		mData.gfriend=(GFriendClientPartData)this.gfriend.makePartData();
		mData.gunion=(GUnionClientPartData)this.gunion.makePartData();
		mData.gteam=(GTeamClientPartData)this.gteam.makePartData();
	}
	
}
