using ShineEngine;

/// <summary>
/// 全局配置表(generated by shine)
/// </summary>
public class HGlobal
{
	/// <summary>
	/// 从流读取
	/// </summary>
	public static void readFromData(HGlobalReadData data)
	{
		
	}
	
	public static void afterReadConfig()
	{

	}
	
	/// <summary>
	/// 全部读取后
	/// </summary>
	public static void afterReadConfigAll()
	{
		
	}
	
}
