using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HCenterRequestType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=17212;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=17212;
	
}
