using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HCenterResponseType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=17112;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=17112;
	
}
