using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HConfigType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=1001;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=1001;
	
}
