using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HGameResponseType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=15312;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=15312;
	
}
