using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HGameRequestType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=15812;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=15812;
	
}
