using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HotfixDataType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=6605;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=6605;
	
}
