using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HPlayerListDataType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=13311;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=13312;
	
	/// <summary>
	/// 热更角色数据
	/// </summary>
	public const int HPlayer=13311;
	
}
