using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HPlayerPartDataType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=13110;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=13110;
	
}
