using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HSceneBaseResponseType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=16312;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=16312;
	
}
