using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HSceneBaseRequestType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=16512;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=16512;
	
}
