using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HSceneResponseType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=16712;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=16712;
	
}
