using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HSceneRequestType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=16912;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=16912;
	
}
