using ShineEngine;

/// <summary>
/// 程序文本枚举(generated by shine)
/// </summary>
public class HTextEnum
{
	/// <summary>
	/// 从配置读取
	/// </summary>
	public static void readConfig()
	{
		
	}
	
}
