package com.home.base.control;

/** (generated by shine) */
public class GCodeCheckRecord
{
	/** 配置文件代码版本校验值 */
	public static final String configMD5="0da5669b0209a71d388e2df2b9f5e4a2";
	
	/** 配置文件代码数据结构版本号 */
	public static final int configVersion=89665346;
	
}
