package com.home.base.control;
import com.home.base.constlist.generate.GTriggerFunctionType;
import com.home.commonBase.control.TriggerControl;
import com.home.shine.constlist.STriggerObjectType;

/** trigger控制(generated by shine) */
public class GTriggerControl extends TriggerControl
{
	/** 注册返回值 */
	@Override
	protected void registReturnType()
	{
		super.registReturnType();
		
		funcReturnTypeDic[GTriggerFunctionType.GTestFunc]=STriggerObjectType.Void;
		funcNameDic[GTriggerFunctionType.GTestFunc]="gTestFunc";
	}
	
}
