package com.home.base.control;

/** (generated by shine) */
public class HCodeCheckRecord
{
	/** 配置文件代码版本校验值 */
	public static final String configMD5="ac9c542684f271e7215c00369bbb793e";
	
	/** 存库数据结构校验 */
	public static final String dbDataMD5="e3c2e9ad420ad70dcce9c5758bc9663c";
	
	/** 数据库版本 */
	public static final int dbDataVersion=7677851;
	
	/** 通信存库数据结构校验 */
	public static final String msgDataMD5="2e39063a8d666ae9e22d00a6e2824166";
	
	/** 通信数据结构版本号(只记录不兼容修改) */
	public static final int msgDataVersion=11213386;
	
	/** 上次数据库版本(dbUpdate用) */
	public static final int lastDBDataVersion=70888716;
	
	/** 配置文件代码数据结构版本号 */
	public static final int configVersion=79145925;
	
}
