package com.home.center.tool.generate;
import com.home.center.constlist.generate.GCenterRequestType;
import com.home.center.constlist.generate.GCenterResponseType;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class GCenterResponseBindTool extends MessageBindTool
{
	public GCenterResponseBindTool()
	{
		offSet=GCenterResponseType.off;
		list=new int[GCenterResponseType.count-offSet][];
	}
	
}
