package com.home.center.tool.generate;
import com.home.center.constlist.generate.GCenterResponseType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class GCenterResponseMaker extends DataMaker
{
	public GCenterResponseMaker()
	{
		offSet=GCenterResponseType.off;
		list=new CreateDataFunc[GCenterResponseType.count-offSet];
	}
	
}
