package com.home.center.tool.generate;
import com.home.center.constlist.generate.HCenterRequestType;
import com.home.center.constlist.generate.HCenterResponseType;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class HCenterResponseBindTool extends MessageBindTool
{
	public HCenterResponseBindTool()
	{
		offSet=HCenterResponseType.off;
		list=new int[HCenterResponseType.count-offSet][];
	}
	
}
