using ShineEngine;
using UnityEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HLoginUI:GameUIBase
{
	/// <summary>
	/// 玩家对象
	/// </summary>
	public HPlayer hme=HGameC.player;
	
	/** UI模型 */
	private UIModel_loginUI _model;

	private Color _color;

	private int _tweenIndex=-1;

	private bool _clickPageOpen=false;

	protected override UIModel createModel()
	{
		return _model=new UIModel_loginUI();
	}
	
	protected override void registLogics()
	{
		base.registLogics();
		
	}
	
	protected override void init()
	{
		base.init();

		_color=_model.clickToPlay.image.color;
		_model.clickToPlay.setActive(false);
		_model.youkeLogin.setActive(false);
		_model.wxLogin.setActive(false);

		_model.getPointer().onClick=()=>
		{
			if(!_clickPageOpen)
				return;

			hide();

			Ctrl.print("当前uid：" + GameC.main.uid);
			HGameC.main.inputUserOver();
		};

		_model.wxLogin.click=()=>
		{
			Ctrl.print("点击微信登录");
		};

		_model.youkeLogin.click=()=>
		{
			setClickPageOpen(true);
			setLoginButtonsVisible(false);
		};

	}
	
	protected override void dispose()
	{
		base.dispose();

		setClickPageOpen(false);
	}
	
	protected override void onEnter()
	{
		base.onEnter();

		ClientLoginCacheData cacheData=(ClientLoginCacheData)_showArgs[0];

		if(cacheData==null)
		{
			setClickPageOpen(false);
			setLoginButtonsVisible(true);
		}
		else
		{
			setClickPageOpen(true);
			setLoginButtonsVisible(false);
		}
	}
	
	protected override void onExit()
	{
		base.onExit();

		setClickPageOpen(false);
	}

	private void setClickPageOpen(bool isOpen)
	{
		if(_clickPageOpen==isOpen)
			return;

		_clickPageOpen=isOpen;

		if(isOpen)
		{
			_model.clickToPlay.setActive(true);

			_tweenIndex=Tween.normal.createTween(0.3f,1,800,v=>
			{
				_color.a=v;
				_model.clickToPlay.image.color=_color;
			}).setRecycle(true).index;
		}
		else
		{
			_model.clickToPlay.setActive(false);

			Tween.normal.kill(_tweenIndex);
			_tweenIndex=-1;
		}
	}

	private void setLoginButtonsVisible(bool isOpen)
	{
		_model.wxLogin.setActive(false);  //TODO:暂时屏蔽微信
		_model.youkeLogin.setActive(isOpen);
	}
}
