package com.home.gmClient.constlist.generate;

/** (generated by shine) */
public class GManagerHttpRequestType
{
	/** 起始 */
	public static final int off=11005;
	
	/** 计数 */
	public static final int count=11005;
	
}
