package com.home.gmClient.constlist.generate;

/** (generated by shine) */
public class GManagerHttpResponseResultType
{
	/** 起始 */
	public static final int off=10805;
	
	/** 计数 */
	public static final int count=10805;
	
}
