package com.home.base.part.centerGlobal.list;
import com.home.base.constlist.generate.GCenterGlobalListDataType;
import com.home.base.part.centerGlobal.data.GCenterFuncPartData;
import com.home.base.part.centerGlobal.data.GCenterUnionPartData;
import com.home.commonBase.part.centerGlobal.data.CenterActivityPartData;
import com.home.commonBase.part.centerGlobal.data.CenterFuncPartData;
import com.home.commonBase.part.centerGlobal.data.CenterMailPartData;
import com.home.commonBase.part.centerGlobal.data.CenterSocialPartData;
import com.home.commonBase.part.centerGlobal.data.CenterSystemPartData;
import com.home.commonBase.part.centerGlobal.list.CenterGlobalListData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 中心服列表数据(generated by shine) */
public class GCenterGlobalListData extends CenterGlobalListData
{
	/** 数据类型ID */
	public static final int dataID=GCenterGlobalListDataType.GCenterGlobal;
	
	public GCenterUnionPartData gunion;
	
	public GCenterFuncPartData gfunc;
	
	public GCenterGlobalListData()
	{
		_dataID=GCenterGlobalListDataType.GCenterGlobal;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "GCenterGlobalListData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		stream.startReadObj();
		
		BaseData systemT=stream.readDataFullNotNull();
		if(systemT!=null)
		{
			if(systemT instanceof CenterSystemPartData)
			{
				this.system=(CenterSystemPartData)systemT;
			}
			else
			{
				this.system=new CenterSystemPartData();
				if(!(systemT.getClass().isAssignableFrom(CenterSystemPartData.class)))
				{
					stream.throwTypeReadError(CenterSystemPartData.class,systemT.getClass());
				}
				this.system.shadowCopy(systemT);
			}
		}
		else
		{
			this.system=null;
		}
		
		BaseData socialT=stream.readDataFullNotNull();
		if(socialT!=null)
		{
			if(socialT instanceof CenterSocialPartData)
			{
				this.social=(CenterSocialPartData)socialT;
			}
			else
			{
				this.social=new CenterSocialPartData();
				if(!(socialT.getClass().isAssignableFrom(CenterSocialPartData.class)))
				{
					stream.throwTypeReadError(CenterSocialPartData.class,socialT.getClass());
				}
				this.social.shadowCopy(socialT);
			}
		}
		else
		{
			this.social=null;
		}
		
		BaseData gfuncT=stream.readDataFullNotNull();
		if(gfuncT!=null)
		{
			if(gfuncT instanceof GCenterFuncPartData)
			{
				this.gfunc=(GCenterFuncPartData)gfuncT;
			}
			else
			{
				this.gfunc=new GCenterFuncPartData();
				if(!(gfuncT.getClass().isAssignableFrom(GCenterFuncPartData.class)))
				{
					stream.throwTypeReadError(GCenterFuncPartData.class,gfuncT.getClass());
				}
				this.gfunc.shadowCopy(gfuncT);
			}
		}
		else
		{
			this.gfunc=null;
		}
		
		BaseData activityT=stream.readDataFullNotNull();
		if(activityT!=null)
		{
			if(activityT instanceof CenterActivityPartData)
			{
				this.activity=(CenterActivityPartData)activityT;
			}
			else
			{
				this.activity=new CenterActivityPartData();
				if(!(activityT.getClass().isAssignableFrom(CenterActivityPartData.class)))
				{
					stream.throwTypeReadError(CenterActivityPartData.class,activityT.getClass());
				}
				this.activity.shadowCopy(activityT);
			}
		}
		else
		{
			this.activity=null;
		}
		
		BaseData mailT=stream.readDataFullNotNull();
		if(mailT!=null)
		{
			if(mailT instanceof CenterMailPartData)
			{
				this.mail=(CenterMailPartData)mailT;
			}
			else
			{
				this.mail=new CenterMailPartData();
				if(!(mailT.getClass().isAssignableFrom(CenterMailPartData.class)))
				{
					stream.throwTypeReadError(CenterMailPartData.class,mailT.getClass());
				}
				this.mail.shadowCopy(mailT);
			}
		}
		else
		{
			this.mail=null;
		}
		
		BaseData gunionT=stream.readDataFullNotNull();
		if(gunionT!=null)
		{
			if(gunionT instanceof GCenterUnionPartData)
			{
				this.gunion=(GCenterUnionPartData)gunionT;
			}
			else
			{
				this.gunion=new GCenterUnionPartData();
				if(!(gunionT.getClass().isAssignableFrom(GCenterUnionPartData.class)))
				{
					stream.throwTypeReadError(GCenterUnionPartData.class,gunionT.getClass());
				}
				this.gunion.shadowCopy(gunionT);
			}
		}
		else
		{
			this.gunion=null;
		}
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		stream.startWriteObj();
		
		if(this.system!=null)
		{
			stream.writeDataFullNotNull(this.system);
		}
		else
		{
			nullObjError("system");
		}
		
		if(this.social!=null)
		{
			stream.writeDataFullNotNull(this.social);
		}
		else
		{
			nullObjError("social");
		}
		
		if(this.gfunc!=null)
		{
			stream.writeDataFullNotNull(this.gfunc);
		}
		else
		{
			nullObjError("gfunc");
		}
		
		if(this.activity!=null)
		{
			stream.writeDataFullNotNull(this.activity);
		}
		else
		{
			nullObjError("activity");
		}
		
		if(this.mail!=null)
		{
			stream.writeDataFullNotNull(this.mail);
		}
		else
		{
			nullObjError("mail");
		}
		
		if(this.gunion!=null)
		{
			stream.writeDataFullNotNull(this.gunion);
		}
		else
		{
			nullObjError("gunion");
		}
		
		stream.endWriteObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		this.system=(CenterSystemPartData)stream.readDataSimpleNotNull();
		
		this.social=(CenterSocialPartData)stream.readDataSimpleNotNull();
		
		this.gfunc=(GCenterFuncPartData)stream.readDataSimpleNotNull();
		
		this.activity=(CenterActivityPartData)stream.readDataSimpleNotNull();
		
		this.mail=(CenterMailPartData)stream.readDataSimpleNotNull();
		
		this.gunion=(GCenterUnionPartData)stream.readDataSimpleNotNull();
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		if(this.system!=null)
		{
			stream.writeDataSimpleNotNull(this.system);
		}
		else
		{
			nullObjError("system");
		}
		
		if(this.social!=null)
		{
			stream.writeDataSimpleNotNull(this.social);
		}
		else
		{
			nullObjError("social");
		}
		
		if(this.gfunc!=null)
		{
			stream.writeDataSimpleNotNull(this.gfunc);
		}
		else
		{
			nullObjError("gfunc");
		}
		
		if(this.activity!=null)
		{
			stream.writeDataSimpleNotNull(this.activity);
		}
		else
		{
			nullObjError("activity");
		}
		
		if(this.mail!=null)
		{
			stream.writeDataSimpleNotNull(this.mail);
		}
		else
		{
			nullObjError("mail");
		}
		
		if(this.gunion!=null)
		{
			stream.writeDataSimpleNotNull(this.gunion);
		}
		else
		{
			nullObjError("gunion");
		}
		
	}
	
	/** 复制(潜拷贝) */
	@Override
	protected void toShadowCopy(BaseData data)
	{
		if(!(data instanceof GCenterGlobalListData))
			return;
		
		GCenterGlobalListData mData=(GCenterGlobalListData)data;
		
		this.system=mData.system;
		this.social=mData.social;
		this.gfunc=mData.gfunc;
		this.activity=mData.activity;
		this.mail=mData.mail;
		this.gunion=mData.gunion;
	}
	
	/** 复制(深拷贝) */
	@Override
	protected void toCopy(BaseData data)
	{
		if(!(data instanceof GCenterGlobalListData))
			return;
		
		GCenterGlobalListData mData=(GCenterGlobalListData)data;
		
		if(mData.system!=null)
		{
			this.system=(CenterSystemPartData)mData.system.clone();
		}
		else
		{
			this.system=null;
			nullObjError("system");
		}
		
		if(mData.social!=null)
		{
			this.social=(CenterSocialPartData)mData.social.clone();
		}
		else
		{
			this.social=null;
			nullObjError("social");
		}
		
		if(mData.gfunc!=null)
		{
			this.gfunc=(GCenterFuncPartData)mData.gfunc.clone();
		}
		else
		{
			this.gfunc=null;
			nullObjError("gfunc");
		}
		
		if(mData.activity!=null)
		{
			this.activity=(CenterActivityPartData)mData.activity.clone();
		}
		else
		{
			this.activity=null;
			nullObjError("activity");
		}
		
		if(mData.mail!=null)
		{
			this.mail=(CenterMailPartData)mData.mail.clone();
		}
		else
		{
			this.mail=null;
			nullObjError("mail");
		}
		
		if(mData.gunion!=null)
		{
			this.gunion=(GCenterUnionPartData)mData.gunion.clone();
		}
		else
		{
			this.gunion=null;
			nullObjError("gunion");
		}
		
	}
	
	/** 是否数据一致 */
	@Override
	protected boolean toDataEquals(BaseData data)
	{
		GCenterGlobalListData mData=(GCenterGlobalListData)data;
		if(mData.system!=null)
		{
			if(this.system==null)
				return false;
			if(!this.system.dataEquals(mData.system))
				return false;
		}
		else
		{
			if(this.system!=null)
				return false;
		}
		
		if(mData.social!=null)
		{
			if(this.social==null)
				return false;
			if(!this.social.dataEquals(mData.social))
				return false;
		}
		else
		{
			if(this.social!=null)
				return false;
		}
		
		if(mData.gfunc!=null)
		{
			if(this.gfunc==null)
				return false;
			if(!this.gfunc.dataEquals(mData.gfunc))
				return false;
		}
		else
		{
			if(this.gfunc!=null)
				return false;
		}
		
		if(mData.activity!=null)
		{
			if(this.activity==null)
				return false;
			if(!this.activity.dataEquals(mData.activity))
				return false;
		}
		else
		{
			if(this.activity!=null)
				return false;
		}
		
		if(mData.mail!=null)
		{
			if(this.mail==null)
				return false;
			if(!this.mail.dataEquals(mData.mail))
				return false;
		}
		else
		{
			if(this.mail!=null)
				return false;
		}
		
		if(mData.gunion!=null)
		{
			if(this.gunion==null)
				return false;
			if(!this.gunion.dataEquals(mData.gunion))
				return false;
		}
		else
		{
			if(this.gunion!=null)
				return false;
		}
		
		return true;
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		writer.writeTabs();
		writer.sb.append("system");
		writer.sb.append(':');
		if(this.system!=null)
		{
			this.system.writeDataString(writer);
		}
		else
		{
			writer.sb.append("CenterSystemPartData=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("social");
		writer.sb.append(':');
		if(this.social!=null)
		{
			this.social.writeDataString(writer);
		}
		else
		{
			writer.sb.append("CenterSocialPartData=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("gfunc");
		writer.sb.append(':');
		if(this.gfunc!=null)
		{
			this.gfunc.writeDataString(writer);
		}
		else
		{
			writer.sb.append("GCenterFuncPartData=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("activity");
		writer.sb.append(':');
		if(this.activity!=null)
		{
			this.activity.writeDataString(writer);
		}
		else
		{
			writer.sb.append("CenterActivityPartData=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("mail");
		writer.sb.append(':');
		if(this.mail!=null)
		{
			this.mail.writeDataString(writer);
		}
		else
		{
			writer.sb.append("CenterMailPartData=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("gunion");
		writer.sb.append(':');
		if(this.gunion!=null)
		{
			this.gunion.writeDataString(writer);
		}
		else
		{
			writer.sb.append("GCenterUnionPartData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 初始化列表数据 */
	@Override
	public void initListData()
	{
		system=new CenterSystemPartData();
		social=new CenterSocialPartData();
		gfunc=new GCenterFuncPartData();
		func=gfunc;
		activity=new CenterActivityPartData();
		mail=new CenterMailPartData();
		gunion=new GCenterUnionPartData();
		union=gunion;
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		this.system=null;
		this.social=null;
		this.gfunc=null;
		this.activity=null;
		this.mail=null;
		this.gunion=null;
	}
	
}
