using ShineEngine;

/// <summary>
/// 控制单位改变设计朝向消息(generated by shine)
/// </summary>
public class CUnitChangeShootDirRequest:CUnitRRequest
{
	/// <summary>
	/// 数据类型ID
	/// </summary>
	public const int dataID=GSceneBaseRequestType.CUnitChangeShootDir;
	
	/// <summary>
	/// 朝向
	/// </summary>
	public DirData dir;
	
	public CUnitChangeShootDirRequest()
	{
		_dataID=GSceneBaseRequestType.CUnitChangeShootDir;
	}
	
	protected override void copyData()
	{
		base.copyData();
		DirData dirTemp=dir;
		if(dirTemp!=null)
		{
			this.dir=(DirData)BytesControl.createData(DirData.dataID);
			this.dir.copy(dirTemp);
		}
		else
		{
			this.dir=null;
		}
		
	}
	
	/// <summary>
	/// 获取数据类名
	/// </summary>
	public override string getDataClassName()
	{
		return "CUnitChangeShootDirRequest";
	}
	
	/// <summary>
	/// 写入字节流(简版)
	/// </summary>
	protected override void toWriteBytesSimple(BytesWriteStream stream)
	{
		base.toWriteBytesSimple(stream);
		
		if(this.dir!=null)
		{
			stream.writeBoolean(true);
			this.dir.writeBytesSimple(stream);
		}
		else
		{
			stream.writeBoolean(false);
		}
		
	}
	
	/// <summary>
	/// 转文本输出
	/// </summary>
	protected override void toWriteDataString(DataWriter writer)
	{
		base.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.Append("dir");
		writer.sb.Append(':');
		if(this.dir!=null)
		{
			this.dir.writeDataString(writer);
		}
		else
		{
			writer.sb.Append("DirData=null");
		}
		
		writer.writeEnter();
	}
	
	/// <summary>
	/// 回池
	/// </summary>
	protected override void toRelease(DataPool pool)
	{
		base.toRelease(pool);
		
		if(this.dir!=null)
		{
			this.dir.release(pool);
			this.dir=null;
		}
	}
	
	/// <summary>
	/// 创建实例
	/// </summary>
	public static CUnitChangeShootDirRequest create(int instanceID,DirData dir)
	{
		CUnitChangeShootDirRequest re=(CUnitChangeShootDirRequest)BytesControl.createRequest(dataID);
		re.instanceID=instanceID;
		re.dir=dir;
		return re;
	}
	
}
