using ShineEngine;
using UnityEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class UIModel_loginUI:UIModel
{
	public UIButton youkeLogin;
	
	public UIButton wxLogin;
	
	public UIImage clickToPlay;
	
	public override void init(GameObject obj)
	{
		base.init(obj);
		
		ElementInfo[] exports=obj.transform.GetComponent<UIElementComponent>().exports;
		
		youkeLogin=new UIButton();
		youkeLogin.name="youkeLogin";
		youkeLogin.init(exports[0].obj);
		registChild(youkeLogin);
		
		wxLogin=new UIButton();
		wxLogin.name="wxLogin";
		wxLogin.init(exports[1].obj);
		registChild(wxLogin);
		
		clickToPlay=new UIImage();
		clickToPlay.name="clickToPlay";
		clickToPlay.init(exports[2].obj);
		registChild(clickToPlay);
		
	}
	
}
