using ShineEngine;
using UnityEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class UIModel_mainUI:UIModel
{
	public UIButton Button_start;
	
	public override void init(GameObject obj)
	{
		base.init(obj);
		
		ElementInfo[] exports=obj.transform.GetComponent<UIElementComponent>().exports;
		
		Button_start=new UIButton();
		Button_start.name="Button_start";
		Button_start.init(exports[0].obj);
		registChild(Button_start);
		
	}
	
}
