using ShineEngine;
using UnityEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class UIModel_fightUI:UIModel
{
	public UIElement_joystick joystickLeft;
	
	public UIElement_joystick joystickRight;
	
	public override void init(GameObject obj)
	{
		base.init(obj);
		
		ElementInfo[] exports=obj.transform.GetComponent<UIElementComponent>().exports;
		
		joystickLeft=new UIElement_joystick();
		joystickLeft.name="joystickLeft";
		joystickLeft.init(exports[0].obj);
		registChild(joystickLeft);
		
		joystickRight=new UIElement_joystick();
		joystickRight.name="joystickRight";
		joystickRight.init(exports[1].obj);
		registChild(joystickRight);
		
	}
	
}
