using ShineEngine;
using UnityEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class UIModel_npcHead:UIModel
{
	public UIText nameText;
	
	public UIImage blood;
	
	public override void init(GameObject obj)
	{
		base.init(obj);
		
		ElementInfo[] exports=obj.transform.GetComponent<UIElementComponent>().exports;
		
		nameText=new UIText();
		nameText.name="nameText";
		nameText.init(exports[0].obj);
		registChild(nameText);
		
		blood=new UIImage();
		blood.name="blood";
		blood.init(exports[1].obj);
		registChild(blood);
		
	}
	
}
