using ShineEngine;
using UnityEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class UIModel_damageNum:UIModel
{
	public UIText txt;
	
	public override void init(GameObject obj)
	{
		base.init(obj);
		
		ElementInfo[] exports=obj.transform.GetComponent<UIElementComponent>().exports;
		
		txt=new UIText();
		txt.name="txt";
		txt.init(exports[0].obj);
		registChild(txt);
		
	}
	
}
