package com.home.base.data.social.union;
import com.home.base.constlist.generate.GBaseDataType;
import com.home.base.constlist.generate.GRoleGroupChangeType;
import com.home.commonBase.data.social.roleGroup.RoleGroupChangeData;
import com.home.commonBase.data.social.union.UnionSimpleData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** g层工会简版数据(generated by shine) */
public class GUnionSimpleData extends UnionSimpleData
{
	public int score;
	
	/** 数据类型ID */
	public static final int dataID=GBaseDataType.GUnionSimple;
	
	public int nice;
	
	public GUnionSimpleData()
	{
		_dataID=GBaseDataType.GUnionSimple;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "GUnionSimpleData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.score=stream.readInt();
		
		this.nice=stream.readInt();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeInt(this.score);
		
		stream.writeInt(this.nice);
		
		stream.endWriteObj();
	}
	
	@Override
	public void onRoleGroupChange(RoleGroupChangeData data)
	{
		super.onRoleGroupChange(data);
		
		switch(data.type)
		{
			case GRoleGroupChangeType.Score:
			{
				score=data.arg0;
			}
				break;
			case GRoleGroupChangeType.Nice:
			{
				nice=data.arg0;
			}
				break;
		}
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.score=stream.readInt();
		
		this.nice=stream.readInt();
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.score);
		
		stream.writeInt(this.nice);
		
	}
	
	/** 复制(潜拷贝) */
	@Override
	protected void toShadowCopy(BaseData data)
	{
		super.toShadowCopy(data);
		
		if(!(data instanceof GUnionSimpleData))
			return;
		
		GUnionSimpleData mData=(GUnionSimpleData)data;
		
		this.score=mData.score;
		this.nice=mData.nice;
	}
	
	/** 复制(深拷贝) */
	@Override
	protected void toCopy(BaseData data)
	{
		super.toCopy(data);
		
		if(!(data instanceof GUnionSimpleData))
			return;
		
		GUnionSimpleData mData=(GUnionSimpleData)data;
		
		this.score=mData.score;
		
		this.nice=mData.nice;
		
	}
	
	/** 是否数据一致 */
	@Override
	protected boolean toDataEquals(BaseData data)
	{
		if(!super.toDataEquals(data))
			return false;
		
		GUnionSimpleData mData=(GUnionSimpleData)data;
		if(this.score!=mData.score)
			return false;
		
		if(this.nice!=mData.nice)
			return false;
		
		return true;
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("score");
		writer.sb.append(':');
		writer.sb.append(this.score);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("nice");
		writer.sb.append(':');
		writer.sb.append(this.nice);
		
		writer.writeEnter();
	}
	
	/** 初始化初值 */
	@Override
	public void initDefault()
	{
		super.initDefault();
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.score=0;
		this.nice=0;
	}
	
}
