using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class GCenterResponseMaker:DataMaker
{
	public GCenterResponseMaker()
	{
		offSet=GCenterResponseType.off;
		list=new Func<BaseData>[GCenterResponseType.count-offSet];
	}
	
}
