using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class GCenterRequestMaker:DataMaker
{
	public GCenterRequestMaker()
	{
		offSet=GCenterRequestType.off;
		list=new Func<BaseData>[GCenterRequestType.count-offSet];
	}
	
}
