using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class GCenterRequestBindTool:MessageBindTool
{
	public GCenterRequestBindTool()
	{
		offSet=GCenterRequestType.off;
		list=new int[GCenterRequestType.count-offSet][];
	}
	
}
