using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class GGameResponseMaker:DataMaker
{
	public GGameResponseMaker()
	{
		offSet=GGameResponseType.off;
		list=new Func<BaseData>[GGameResponseType.count-offSet];
	}
	
}
