using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class GGameRequestMaker:DataMaker
{
	public GGameRequestMaker()
	{
		offSet=GGameRequestType.off;
		list=new Func<BaseData>[GGameRequestType.count-offSet];
	}
	
}
