using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class GGameRequestBindTool:MessageBindTool
{
	public GGameRequestBindTool()
	{
		offSet=GGameRequestType.off;
		list=new int[GGameRequestType.count-offSet][];
	}
	
}
