using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class GPlayerPartDataMaker:DataMaker
{
	public GPlayerPartDataMaker()
	{
		offSet=GPlayerPartDataType.off;
		list=new Func<BaseData>[GPlayerPartDataType.count-offSet];
		list[GPlayerPartDataType.GBag-offSet]=createGBagPartData;
		list[GPlayerPartDataType.GCharacter-offSet]=createGCharacterPartData;
		list[GPlayerPartDataType.GRole-offSet]=createGRolePartData;
		list[GPlayerPartDataType.GUnion-offSet]=createGUnionPartData;
		list[GPlayerPartDataType.GFriend-offSet]=createGFriendPartData;
		list[GPlayerPartDataType.GFunc-offSet]=createGFuncPartData;
		list[GPlayerPartDataType.GTeam-offSet]=createGTeamPartData;
		list[GPlayerPartDataType.GScene-offSet]=createGScenePartData;
	}
	
	private BaseData createGCharacterPartData()
	{
		return new GCharacterPartData();
	}
	
	private BaseData createGRolePartData()
	{
		return new GRolePartData();
	}
	
	private BaseData createGBagPartData()
	{
		return new GBagPartData();
	}
	
	private BaseData createGUnionPartData()
	{
		return new GUnionPartData();
	}
	
	private BaseData createGFuncPartData()
	{
		return new GFuncPartData();
	}
	
	private BaseData createGFriendPartData()
	{
		return new GFriendPartData();
	}
	
	private BaseData createGTeamPartData()
	{
		return new GTeamPartData();
	}
	
	private BaseData createGScenePartData()
	{
		return new GScenePartData();
	}
	
}
