using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class GPlayerListDataMaker:DataMaker
{
	public GPlayerListDataMaker()
	{
		offSet=GPlayerListDataType.off;
		list=new Func<BaseData>[GPlayerListDataType.count-offSet];
		list[GPlayerListDataType.GPlayer-offSet]=createGPlayerListData;
	}
	
	private BaseData createGPlayerListData()
	{
		return new GPlayerListData();
	}
	
}
