using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class GSceneBaseRequestBindTool:MessageBindTool
{
	public GSceneBaseRequestBindTool()
	{
		offSet=GSceneBaseRequestType.off;
		list=new int[GSceneBaseRequestType.count-offSet][];
	}
	
}
