using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class GSceneResponseMaker:DataMaker
{
	public GSceneResponseMaker()
	{
		offSet=GSceneResponseType.off;
		list=new Func<BaseData>[GSceneResponseType.count-offSet];
	}
	
}
