using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class GSceneRequestBindTool:MessageBindTool
{
	public GSceneRequestBindTool()
	{
		offSet=GSceneRequestType.off;
		list=new int[GSceneRequestType.count-offSet][];
	}
	
}
