using ShineEngine;
using System;

/// <summary>
/// (generated by shine)
/// </summary>
public class GSceneBaseResponseMaker:DataMaker
{
	public GSceneBaseResponseMaker()
	{
		offSet=GSceneBaseResponseType.off;
		list=new Func<BaseData>[GSceneBaseResponseType.count-offSet];
		list[GSceneBaseResponseType.UnitChangeShootDir-offSet]=createUnitChangeShootDirResponse;
	}
	
	private BaseData createUnitChangeShootDirResponse()
	{
		return new UnitChangeShootDirResponse();
	}
	
}
