package com.home.manager.tool.generate;
import com.home.manager.constlist.generate.GManagerHttpResponseType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class GManagerHttpResponseMaker extends DataMaker
{
	public GManagerHttpResponseMaker()
	{
		offSet=GManagerHttpResponseType.off;
		list=new CreateDataFunc[GManagerHttpResponseType.count-offSet];
	}
	
}
