package com.home.client.net.sceneBaseResponse.unit;
import com.home.client.constlist.generate.GSceneBaseResponseType;
import com.home.commonBase.data.scene.base.DirData;
import com.home.commonClient.net.sceneBaseResponse.base.UnitSResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** (generated by shine) */
public class UnitChangeShootDirResponse extends UnitSResponse
{
	/** 数据类型ID */
	public static final int dataID=GSceneBaseResponseType.UnitChangeShootDir;
	
	/** 朝向 */
	public DirData dir;
	
	public UnitChangeShootDirResponse()
	{
		_dataID=GSceneBaseResponseType.UnitChangeShootDir;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "UnitChangeShootDirResponse";
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		if(stream.readBoolean())
		{
			this.dir=new DirData();
			this.dir.readBytesSimple(stream);
		}
		else
		{
			this.dir=null;
		}
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("dir");
		writer.sb.append(':');
		if(this.dir!=null)
		{
			this.dir.writeDataString(writer);
		}
		else
		{
			writer.sb.append("DirData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.dir=null;
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		
	}
	
}
