using ShineEngine;

/// <summary>
/// g层工会简版数据(generated by shine)
/// </summary>
public class GUnionSimpleData:UnionSimpleData
{
	public int score;
	
	/// <summary>
	/// 数据类型ID
	/// </summary>
	public const int dataID=GBaseDataType.GUnionSimple;
	
	public int nice;
	
	public GUnionSimpleData()
	{
		_dataID=GBaseDataType.GUnionSimple;
	}
	
	/// <summary>
	/// 获取数据类名
	/// </summary>
	public override string getDataClassName()
	{
		return "GUnionSimpleData";
	}
	
	/// <summary>
	/// 读取字节流(完整版)
	/// </summary>
	protected override void toReadBytesFull(BytesReadStream stream)
	{
		base.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.score=stream.readInt();
		
		this.nice=stream.readInt();
		
		stream.endReadObj();
	}
	
	/// <summary>
	/// 写入字节流(完整版)
	/// </summary>
	protected override void toWriteBytesFull(BytesWriteStream stream)
	{
		base.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeInt(this.score);
		
		stream.writeInt(this.nice);
		
		stream.endWriteObj();
	}
	
	/// <summary>
	/// 读取字节流(简版)
	/// </summary>
	protected override void toReadBytesSimple(BytesReadStream stream)
	{
		base.toReadBytesSimple(stream);
		
		this.score=stream.readInt();
		
		this.nice=stream.readInt();
		
	}
	
	/// <summary>
	/// 写入字节流(简版)
	/// </summary>
	protected override void toWriteBytesSimple(BytesWriteStream stream)
	{
		base.toWriteBytesSimple(stream);
		
		stream.writeInt(this.score);
		
		stream.writeInt(this.nice);
		
	}
	
	/// <summary>
	/// 复制(潜拷贝)
	/// </summary>
	protected override void toShadowCopy(BaseData data)
	{
		base.toShadowCopy(data);
		
		if(!(data is GUnionSimpleData))
			return;
		
		GUnionSimpleData mData=(GUnionSimpleData)data;
		
		this.score=mData.score;
		this.nice=mData.nice;
	}
	
	/// <summary>
	/// 复制(深拷贝)
	/// </summary>
	protected override void toCopy(BaseData data)
	{
		base.toCopy(data);
		
		if(!(data is GUnionSimpleData))
			return;
		
		GUnionSimpleData mData=(GUnionSimpleData)data;
		
		this.score=mData.score;
		
		this.nice=mData.nice;
		
	}
	
	/// <summary>
	/// 是否数据一致
	/// </summary>
	protected override bool toDataEquals(BaseData data)
	{
		if(!base.toDataEquals(data))
			return false;
		
		GUnionSimpleData mData=(GUnionSimpleData)data;
		if(this.score!=mData.score)
			return false;
		
		if(this.nice!=mData.nice)
			return false;
		
		return true;
	}
	
	/// <summary>
	/// 转文本输出
	/// </summary>
	protected override void toWriteDataString(DataWriter writer)
	{
		base.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.Append("score");
		writer.sb.Append(':');
		writer.sb.Append(this.score);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.Append("nice");
		writer.sb.Append(':');
		writer.sb.Append(this.nice);
		
		writer.writeEnter();
	}
	
	/// <summary>
	/// 初始化初值
	/// </summary>
	public override void initDefault()
	{
		base.initDefault();
		
	}
	
	/// <summary>
	/// 回池
	/// </summary>
	protected override void toRelease(DataPool pool)
	{
		base.toRelease(pool);
		
		this.score=0;
		this.nice=0;
	}
	
}
