using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HCodeCheckRecord
{
	/// <summary>
	/// 配置文件代码版本校验值
	/// </summary>
	public const string configMD5="ac9c542684f271e7215c00369bbb793e";
	
	/// <summary>
	/// 通信存库数据结构校验
	/// </summary>
	public const string msgDataMD5="2e39063a8d666ae9e22d00a6e2824166";
	
	/// <summary>
	/// 通信数据结构版本号(只记录不兼容修改)
	/// </summary>
	public const int msgDataVersion=11213386;
	
	/// <summary>
	/// 配置文件代码数据结构版本号
	/// </summary>
	public const int configVersion=79984250;
	
}
