using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class HGameUI
{
	public static HMainUI main;
	
	public static HFightUI fight;
	
	public static HLoginUI login;
	
	/// <summary>
	/// 初始化UI
	/// </summary>
	public static void init()
	{
		main=new HMainUI();
		main.construct(HUIInstanceType.Main);
		GameC.ui.registUI(main);
		fight=new HFightUI();
		fight.construct(HUIInstanceType.Fight);
		GameC.ui.registUI(fight);
		login=new HLoginUI();
		login.construct(HUIInstanceType.Login);
		GameC.ui.registUI(login);
	}
	
}
