package com.home.game.part.player;
import com.home.base.part.player.clientData.GBagClientPartData;
import com.home.base.part.player.clientData.GCharacterClientPartData;
import com.home.base.part.player.clientData.GFriendClientPartData;
import com.home.base.part.player.clientData.GFuncClientPartData;
import com.home.base.part.player.clientData.GRoleClientPartData;
import com.home.base.part.player.clientData.GSceneClientPartData;
import com.home.base.part.player.clientData.GTeamClientPartData;
import com.home.base.part.player.clientData.GUnionClientPartData;
import com.home.base.part.player.data.GBagPartData;
import com.home.base.part.player.data.GCharacterPartData;
import com.home.base.part.player.data.GFriendPartData;
import com.home.base.part.player.data.GFuncPartData;
import com.home.base.part.player.data.GRolePartData;
import com.home.base.part.player.data.GScenePartData;
import com.home.base.part.player.data.GTeamPartData;
import com.home.base.part.player.data.GUnionPartData;
import com.home.base.part.player.list.GPlayerClientListData;
import com.home.base.part.player.list.GPlayerListData;
import com.home.commonBase.part.player.clientData.ActivityClientPartData;
import com.home.commonBase.part.player.clientData.FriendClientPartData;
import com.home.commonBase.part.player.clientData.GuideClientPartData;
import com.home.commonBase.part.player.clientData.MailClientPartData;
import com.home.commonBase.part.player.clientData.PetClientPartData;
import com.home.commonBase.part.player.clientData.QuestClientPartData;
import com.home.commonBase.part.player.clientData.SceneClientPartData;
import com.home.commonBase.part.player.clientData.SocialClientPartData;
import com.home.commonBase.part.player.clientData.SystemClientPartData;
import com.home.commonBase.part.player.data.ActivityPartData;
import com.home.commonBase.part.player.data.FriendPartData;
import com.home.commonBase.part.player.data.GuidePartData;
import com.home.commonBase.part.player.data.MailPartData;
import com.home.commonBase.part.player.data.PetPartData;
import com.home.commonBase.part.player.data.QuestPartData;
import com.home.commonBase.part.player.data.ScenePartData;
import com.home.commonBase.part.player.data.SocialPartData;
import com.home.commonBase.part.player.data.SystemPartData;
import com.home.commonBase.part.player.list.PlayerClientListData;
import com.home.commonBase.part.player.list.PlayerListData;
import com.home.commonGame.part.player.Player;
import com.home.commonGame.part.player.base.PlayerBasePart;
import com.home.commonGame.part.player.part.ActivityPart;
import com.home.commonGame.part.player.part.FriendPart;
import com.home.commonGame.part.player.part.GuidePart;
import com.home.commonGame.part.player.part.MailPart;
import com.home.commonGame.part.player.part.PetPart;
import com.home.commonGame.part.player.part.QuestPart;
import com.home.commonGame.part.player.part.ScenePart;
import com.home.commonGame.part.player.part.SocialPart;
import com.home.commonGame.part.player.part.SystemPart;
import com.home.game.part.player.part.GBagPart;
import com.home.game.part.player.part.GCharacterPart;
import com.home.game.part.player.part.GFriendPart;
import com.home.game.part.player.part.GFuncPart;
import com.home.game.part.player.part.GRolePart;
import com.home.game.part.player.part.GScenePart;
import com.home.game.part.player.part.GTeamPart;
import com.home.game.part.player.part.GUnionPart;

/** 玩家数据主体(generated by shine) */
public class GPlayer extends Player
{
	/** 角色 */
	public GRolePart grole;
	
	/** 角色 */
	public GCharacterPart gcharacter;
	
	/** 背包 */
	public GBagPart gbag;
	
	/** 工会 */
	public GUnionPart gunion;
	
	/** 功能 */
	public GFuncPart gfunc;
	
	/** 好友 */
	public GFriendPart gfriend;
	
	/** 组队 */
	public GTeamPart gteam;
	
	/** 场景 */
	public GScenePart gscene;
	
	/** 注册部件 */
	@Override
	protected void registParts()
	{
		_list=new PlayerBasePart[14];
		int i=0;
		
		system=new SystemPart();
		system.setMe(this);
		_list[i++]=system;
		
		gfunc=new GFuncPart();
		func=gfunc;
		gfunc.setMe(this);
		_list[i++]=gfunc;
		
		activity=new ActivityPart();
		activity.setMe(this);
		_list[i++]=activity;
		
		grole=new GRolePart();
		role=grole;
		grole.setMe(this);
		_list[i++]=grole;
		
		gscene=new GScenePart();
		scene=gscene;
		gscene.setMe(this);
		_list[i++]=gscene;
		
		gcharacter=new GCharacterPart();
		character=gcharacter;
		gcharacter.setMe(this);
		_list[i++]=gcharacter;
		
		social=new SocialPart();
		social.setMe(this);
		_list[i++]=social;
		
		gbag=new GBagPart();
		bag=gbag;
		gbag.setMe(this);
		_list[i++]=gbag;
		
		mail=new MailPart();
		mail.setMe(this);
		_list[i++]=mail;
		
		quest=new QuestPart();
		quest.setMe(this);
		_list[i++]=quest;
		
		guide=new GuidePart();
		guide.setMe(this);
		_list[i++]=guide;
		
		gfriend=new GFriendPart();
		friend=gfriend;
		gfriend.setMe(this);
		_list[i++]=gfriend;
		
		gunion=new GUnionPart();
		union=gunion;
		gunion.setMe(this);
		_list[i++]=gunion;
		
		gteam=new GTeamPart();
		team=gteam;
		gteam.setMe(this);
		_list[i++]=gteam;
		
	}
	
	/** 创建列表数据 */
	@Override
	public PlayerListData createListData()
	{
		return new GPlayerListData();
	}
	
	/** 从列表数据读取 */
	@Override
	public void readListData(PlayerListData listData)
	{
		GPlayerListData mData=(GPlayerListData)listData;
		
		this.system.setData(mData.system);
		this.gfunc.setData(mData.gfunc);
		this.activity.setData(mData.activity);
		this.grole.setData(mData.grole);
		this.gscene.setData(mData.gscene);
		this.gcharacter.setData(mData.gcharacter);
		this.social.setData(mData.social);
		this.gbag.setData(mData.gbag);
		this.mail.setData(mData.mail);
		this.quest.setData(mData.quest);
		this.guide.setData(mData.guide);
		this.gfriend.setData(mData.gfriend);
		this.gunion.setData(mData.gunion);
		this.gteam.setData(mData.gteam);
	}
	
	/** 写列表数据(深拷) */
	@Override
	public void writeListData(PlayerListData listData)
	{
		GPlayerListData mData=(GPlayerListData)listData;
		
		mData.system=(SystemPartData)this.system.makePartData();
		mData.gfunc=(GFuncPartData)this.gfunc.makePartData();
		mData.activity=(ActivityPartData)this.activity.makePartData();
		mData.grole=(GRolePartData)this.grole.makePartData();
		mData.gscene=(GScenePartData)this.gscene.makePartData();
		mData.gcharacter=(GCharacterPartData)this.gcharacter.makePartData();
		mData.social=(SocialPartData)this.social.makePartData();
		mData.gbag=(GBagPartData)this.gbag.makePartData();
		mData.mail=(MailPartData)this.mail.makePartData();
		mData.quest=(QuestPartData)this.quest.makePartData();
		mData.guide=(GuidePartData)this.guide.makePartData();
		mData.gfriend=(GFriendPartData)this.gfriend.makePartData();
		mData.gunion=(GUnionPartData)this.gunion.makePartData();
		mData.gteam=(GTeamPartData)this.gteam.makePartData();
	}
	
	/** 写列表数据(潜拷) */
	@Override
	public void writeShadowListData(PlayerListData listData)
	{
		GPlayerListData mData=(GPlayerListData)listData;
		
		mData.system=(SystemPartData)this.system.makeShadowPartData();
		mData.gfunc=(GFuncPartData)this.gfunc.makeShadowPartData();
		mData.activity=(ActivityPartData)this.activity.makeShadowPartData();
		mData.grole=(GRolePartData)this.grole.makeShadowPartData();
		mData.gscene=(GScenePartData)this.gscene.makeShadowPartData();
		mData.gcharacter=(GCharacterPartData)this.gcharacter.makeShadowPartData();
		mData.social=(SocialPartData)this.social.makeShadowPartData();
		mData.gbag=(GBagPartData)this.gbag.makeShadowPartData();
		mData.mail=(MailPartData)this.mail.makeShadowPartData();
		mData.quest=(QuestPartData)this.quest.makeShadowPartData();
		mData.guide=(GuidePartData)this.guide.makeShadowPartData();
		mData.gfriend=(GFriendPartData)this.gfriend.makeShadowPartData();
		mData.gunion=(GUnionPartData)this.gunion.makeShadowPartData();
		mData.gteam=(GTeamPartData)this.gteam.makeShadowPartData();
	}
	
	/** 构造客户端列表数据 */
	public PlayerClientListData makeClientListData()
	{
		GPlayerClientListData listData=new GPlayerClientListData();
		
		listData.system=(SystemClientPartData)this.system.makeClientPartData();
		listData.gfunc=(GFuncClientPartData)this.gfunc.makeClientPartData();
		listData.activity=(ActivityClientPartData)this.activity.makeClientPartData();
		listData.grole=(GRoleClientPartData)this.grole.makeClientPartData();
		listData.gscene=(GSceneClientPartData)this.gscene.makeClientPartData();
		listData.gcharacter=(GCharacterClientPartData)this.gcharacter.makeClientPartData();
		listData.social=(SocialClientPartData)this.social.makeClientPartData();
		listData.gbag=(GBagClientPartData)this.gbag.makeClientPartData();
		listData.mail=(MailClientPartData)this.mail.makeClientPartData();
		listData.quest=(QuestClientPartData)this.quest.makeClientPartData();
		listData.guide=(GuideClientPartData)this.guide.makeClientPartData();
		listData.gfriend=(GFriendClientPartData)this.gfriend.makeClientPartData();
		listData.gunion=(GUnionClientPartData)this.gunion.makeClientPartData();
		listData.gteam=(GTeamClientPartData)this.gteam.makeClientPartData();
		
		return listData;
	}
	
}
