package com.home.center.part.centerGlobal;
import com.home.base.part.centerGlobal.data.GCenterFuncPartData;
import com.home.base.part.centerGlobal.data.GCenterUnionPartData;
import com.home.base.part.centerGlobal.list.GCenterGlobalListData;
import com.home.center.part.centerGlobal.part.GCenterFuncPart;
import com.home.center.part.centerGlobal.part.GCenterUnionPart;
import com.home.commonBase.part.centerGlobal.data.CenterActivityPartData;
import com.home.commonBase.part.centerGlobal.data.CenterMailPartData;
import com.home.commonBase.part.centerGlobal.data.CenterSocialPartData;
import com.home.commonBase.part.centerGlobal.data.CenterSystemPartData;
import com.home.commonBase.part.centerGlobal.list.CenterGlobalListData;
import com.home.commonCenter.part.centerGlobal.CenterGlobal;
import com.home.commonCenter.part.centerGlobal.base.CenterGlobalBasePart;
import com.home.commonCenter.part.centerGlobal.part.CenterActivityPart;
import com.home.commonCenter.part.centerGlobal.part.CenterMailPart;
import com.home.commonCenter.part.centerGlobal.part.CenterSocialPart;
import com.home.commonCenter.part.centerGlobal.part.CenterSystemPart;

/** 中心服列表数据(generated by shine) */
public class GCenterGlobal extends CenterGlobal
{
	public GCenterUnionPart gunion;
	
	public GCenterFuncPart gfunc;
	
	/** 注册部件 */
	@Override
	protected void registParts()
	{
		_list=new CenterGlobalBasePart[6];
		int i=0;
		
		system=new CenterSystemPart();
		system.setMe(this);
		_list[i++]=system;
		
		social=new CenterSocialPart();
		social.setMe(this);
		_list[i++]=social;
		
		gfunc=new GCenterFuncPart();
		func=gfunc;
		gfunc.setMe(this);
		_list[i++]=gfunc;
		
		activity=new CenterActivityPart();
		activity.setMe(this);
		_list[i++]=activity;
		
		mail=new CenterMailPart();
		mail.setMe(this);
		_list[i++]=mail;
		
		gunion=new GCenterUnionPart();
		union=gunion;
		gunion.setMe(this);
		_list[i++]=gunion;
		
	}
	
	/** 创建列表数据 */
	@Override
	public CenterGlobalListData createListData()
	{
		return new GCenterGlobalListData();
	}
	
	/** 从列表数据读取 */
	@Override
	public void readListData(CenterGlobalListData listData)
	{
		GCenterGlobalListData mData=(GCenterGlobalListData)listData;
		
		this.system.setData(mData.system);
		this.social.setData(mData.social);
		this.gfunc.setData(mData.gfunc);
		this.activity.setData(mData.activity);
		this.mail.setData(mData.mail);
		this.gunion.setData(mData.gunion);
	}
	
	/** 写列表数据(深拷) */
	@Override
	public void writeListData(CenterGlobalListData listData)
	{
		GCenterGlobalListData mData=(GCenterGlobalListData)listData;
		
		mData.system=(CenterSystemPartData)this.system.makePartData();
		mData.social=(CenterSocialPartData)this.social.makePartData();
		mData.gfunc=(GCenterFuncPartData)this.gfunc.makePartData();
		mData.activity=(CenterActivityPartData)this.activity.makePartData();
		mData.mail=(CenterMailPartData)this.mail.makePartData();
		mData.gunion=(GCenterUnionPartData)this.gunion.makePartData();
	}
	
	/** 写列表数据(潜拷) */
	@Override
	public void writeShadowListData(CenterGlobalListData listData)
	{
		GCenterGlobalListData mData=(GCenterGlobalListData)listData;
		
		mData.system=(CenterSystemPartData)this.system.makeShadowPartData();
		mData.social=(CenterSocialPartData)this.social.makeShadowPartData();
		mData.gfunc=(GCenterFuncPartData)this.gfunc.makeShadowPartData();
		mData.activity=(CenterActivityPartData)this.activity.makeShadowPartData();
		mData.mail=(CenterMailPartData)this.mail.makeShadowPartData();
		mData.gunion=(GCenterUnionPartData)this.gunion.makeShadowPartData();
	}
	
}
