/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_home_base_extern_GExternMethodNative */

#ifndef _Included_com_home_base_extern_GExternMethodNative
#define _Included_com_home_base_extern_GExternMethodNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_home_base_extern_GExternMethodNative
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_home_base_extern_GExternMethodNative_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
