using ShineEngine;

/// <summary>
/// 功能表(generated by shine)
/// </summary>
public class GFunctionConfig:FunctionConfig
{
	/** 存储集合 */
	private static IntObjectMap<GFunctionConfig> _dic;
	
	/// <summary>
	/// 开关ID
	/// </summary>
	public int switchID;
	
	/// <summary>
	/// 获取
	/// </summary>
	public static GFunctionConfig getG(int id)
	{
		return _dic.get(id);
	}
	
	/// <summary>
	/// 设置字典
	/// </summary>
	public static void setGDic(IntObjectMap<GFunctionConfig> dic)
	{
		_dic=dic;
	}
	
	/// <summary>
	/// 添加字典(热更用)
	/// </summary>
	public static void addGDic(IntObjectMap<GFunctionConfig> dic)
	{
		_dic.putAll(dic);
	}
	
	/// <summary>
	/// 获取全部
	/// </summary>
	public static IntObjectMap<GFunctionConfig> getGDic()
	{
		return _dic;
	}
	
	/// <summary>
	/// 读取字节流(简版)
	/// </summary>
	protected override void toReadBytesSimple(BytesReadStream stream)
	{
		base.toReadBytesSimple(stream);
		
		this.switchID=stream.readShort();
		
	}
	
	/// <summary>
	/// 写入字节流(简版)
	/// </summary>
	protected override void toWriteBytesSimple(BytesWriteStream stream)
	{
		base.toWriteBytesSimple(stream);
		
		stream.writeShort(this.switchID);
		
	}
	
	/// <summary>
	/// 读完所有表后处理
	/// </summary>
	public static void afterReadConfigAll()
	{
		
	}
	
}
