package com.home.center.constlist.generate;

/** (generated by shine) */
public class GCenterRequestType
{
	/** 起始 */
	public static final int off=10205;
	
	/** 计数 */
	public static final int count=10205;
	
}
