package com.home.center.constlist.generate;

/** (generated by shine) */
public class GCenterResponseType
{
	/** 起始 */
	public static final int off=10405;
	
	/** 计数 */
	public static final int count=10405;
	
}
