package com.home.center.constlist.generate;

/** (generated by shine) */
public class HCenterRequestType
{
	/** 起始 */
	public static final int off=17112;
	
	/** 计数 */
	public static final int count=17112;
	
}
