package com.home.center.constlist.generate;

/** (generated by shine) */
public class HCenterResponseType
{
	/** 起始 */
	public static final int off=17212;
	
	/** 计数 */
	public static final int count=17212;
	
}
