package com.home.base.data.role;
import com.home.base.constlist.generate.GBaseDataType;
import com.home.commonBase.data.role.CharacterSaveData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.collection.IntIntMap;

/** 角色存库信息(跟CharacterCacheDO没有关系)(generated by shine) */
public class GCharacterSaveData extends CharacterSaveData
{
	/** 数据类型ID */
	public static final int dataID=GBaseDataType.GCharacterSave;
	
	/** 星级 */
	public int stars;
	
	/** 血统 */
	public int skillExp;
	
	/** 天赋组 */
	public IntIntMap talents;
	
	public GCharacterSaveData()
	{
		_dataID=GBaseDataType.GCharacterSave;
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.endWriteObj();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "GCharacterSaveData";
	}
	
}
