package com.home.base.data.role;
import com.home.base.constlist.generate.GBaseDataType;
import com.home.commonBase.data.role.RoleShowChangeData;
import com.home.commonBase.data.role.RoleShowData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;

/** 角色外显数据(generated by shine) */
public class GRoleShowData extends RoleShowData
{
	/** 数据类型ID */
	public static final int dataID=GBaseDataType.GRoleShow;
	
	/** 头像 */
	public int portrait;
	
	/** 大乱斗等级 */
	public int meleeLevel;
	
	/** 当前选择角色ID */
	public int selectCharacterID;
	
	/** 大乱斗称号 */
	public int meleeTitle;
	
	public GRoleShowData()
	{
		_dataID=GBaseDataType.GRoleShow;
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.endWriteObj();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "GRoleShowData";
	}
	
	@Override
	public void onChange(RoleShowChangeData data)
	{
		switch(data.type)
		{
		
		}
		
		super.onChange(data);
	}
	
}
