package com.home.base.part.centerGlobal.data;
import com.home.base.constlist.generate.GCenterGlobalPartDataType;
import com.home.commonBase.part.centerGlobal.data.CenterUnionPartData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;

/** (generated by shine) */
public class GCenterUnionPartData extends CenterUnionPartData
{
	/** 数据类型ID */
	public static final int dataID=GCenterGlobalPartDataType.GCenterUnion;
	
	public GCenterUnionPartData()
	{
		_dataID=GCenterGlobalPartDataType.GCenterUnion;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "GCenterUnionPartData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.endWriteObj();
	}
	
}
