package com.home.base.tool.generate;
import com.home.base.constlist.generate.GBaseDataType;
import com.home.base.data.login.GGameLoginData;
import com.home.base.data.role.GCharacterSaveData;
import com.home.base.data.role.GCharacterUseData;
import com.home.base.data.role.GRoleShowData;
import com.home.base.data.scene.unit.GCharacterIdentityData;
import com.home.base.data.scene.unit.GUnitPosData;
import com.home.base.data.social.union.GUnionData;
import com.home.base.data.social.union.GUnionSimpleData;
import com.home.shine.data.BaseData;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class GBaseDataMaker extends DataMaker
{
	public GBaseDataMaker()
	{
		offSet=GBaseDataType.off;
		list=new CreateDataFunc[GBaseDataType.count-offSet];
		list[GBaseDataType.GCharacterIdentity-offSet]=this::createGCharacterIdentityData;
		list[GBaseDataType.GCharacterSave-offSet]=this::createGCharacterSaveData;
		list[GBaseDataType.GCharacterUse-offSet]=this::createGCharacterUseData;
		list[GBaseDataType.GGameLogin-offSet]=this::createGGameLoginData;
		list[GBaseDataType.GRoleShow-offSet]=this::createGRoleShowData;
		list[GBaseDataType.GUnion-offSet]=this::createGUnionData;
		list[GBaseDataType.GUnionSimple-offSet]=this::createGUnionSimpleData;
		list[GBaseDataType.GUnitPos-offSet]=this::createGUnitPosData;
	}
	
	private BaseData createGCharacterIdentityData()
	{
		return new GCharacterIdentityData();
	}
	
	private BaseData createGCharacterSaveData()
	{
		return new GCharacterSaveData();
	}
	
	private BaseData createGCharacterUseData()
	{
		return new GCharacterUseData();
	}
	
	private BaseData createGGameLoginData()
	{
		return new GGameLoginData();
	}
	
	private BaseData createGRoleShowData()
	{
		return new GRoleShowData();
	}
	
	private BaseData createGUnionData()
	{
		return new GUnionData();
	}
	
	private BaseData createGUnionSimpleData()
	{
		return new GUnionSimpleData();
	}
	
	private BaseData createGUnitPosData()
	{
		return new GUnitPosData();
	}
	
}
