package com.home.base.tool.generate;
import com.home.base.constlist.generate.GCenterGlobalListDataType;
import com.home.base.part.centerGlobal.list.GCenterGlobalListData;
import com.home.shine.data.BaseData;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class GCenterGlobalListDataMaker extends DataMaker
{
	public GCenterGlobalListDataMaker()
	{
		offSet=GCenterGlobalListDataType.off;
		list=new CreateDataFunc[GCenterGlobalListDataType.count-offSet];
		list[GCenterGlobalListDataType.GCenterGlobal-offSet]=this::createGCenterGlobalListData;
	}
	
	private BaseData createGCenterGlobalListData()
	{
		return new GCenterGlobalListData();
	}
	
}
