package com.home.base.tool.generate;
import com.home.base.constlist.generate.GGameGlobalListDataType;
import com.home.base.part.gameGlobal.list.GGameGlobalListData;
import com.home.shine.data.BaseData;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class GGameGlobalListDataMaker extends DataMaker
{
	public GGameGlobalListDataMaker()
	{
		offSet=GGameGlobalListDataType.off;
		list=new CreateDataFunc[GGameGlobalListDataType.count-offSet];
		list[GGameGlobalListDataType.GGameGlobal-offSet]=this::createGGameGlobalListData;
	}
	
	private BaseData createGGameGlobalListData()
	{
		return new GGameGlobalListData();
	}
	
}
