package com.home.base.tool.generate;
import com.home.base.constlist.generate.GPlayerPartDataType;
import com.home.base.part.player.data.GBagPartData;
import com.home.base.part.player.data.GCharacterPartData;
import com.home.base.part.player.data.GFriendPartData;
import com.home.base.part.player.data.GFuncPartData;
import com.home.base.part.player.data.GRolePartData;
import com.home.base.part.player.data.GScenePartData;
import com.home.base.part.player.data.GTeamPartData;
import com.home.base.part.player.data.GUnionPartData;
import com.home.shine.data.BaseData;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class GPlayerPartDataMaker extends DataMaker
{
	public GPlayerPartDataMaker()
	{
		offSet=GPlayerPartDataType.off;
		list=new CreateDataFunc[GPlayerPartDataType.count-offSet];
		list[GPlayerPartDataType.GBag-offSet]=this::createGBagPartData;
		list[GPlayerPartDataType.GCharacter-offSet]=this::createGCharacterPartData;
		list[GPlayerPartDataType.GRole-offSet]=this::createGRolePartData;
		list[GPlayerPartDataType.GUnion-offSet]=this::createGUnionPartData;
		list[GPlayerPartDataType.GFriend-offSet]=this::createGFriendPartData;
		list[GPlayerPartDataType.GFunc-offSet]=this::createGFuncPartData;
		list[GPlayerPartDataType.GTeam-offSet]=this::createGTeamPartData;
		list[GPlayerPartDataType.GScene-offSet]=this::createGScenePartData;
	}
	
	private BaseData createGBagPartData()
	{
		return new GBagPartData();
	}
	
	private BaseData createGCharacterPartData()
	{
		return new GCharacterPartData();
	}
	
	private BaseData createGRolePartData()
	{
		return new GRolePartData();
	}
	
	private BaseData createGUnionPartData()
	{
		return new GUnionPartData();
	}
	
	private BaseData createGFuncPartData()
	{
		return new GFuncPartData();
	}
	
	private BaseData createGFriendPartData()
	{
		return new GFriendPartData();
	}
	
	private BaseData createGTeamPartData()
	{
		return new GTeamPartData();
	}
	
	private BaseData createGScenePartData()
	{
		return new GScenePartData();
	}
	
}
