package com.home.base.tool.generate;
import com.home.base.constlist.generate.GPlayerListDataType;
import com.home.base.part.player.list.GPlayerListData;
import com.home.shine.data.BaseData;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class GPlayerListDataMaker extends DataMaker
{
	public GPlayerListDataMaker()
	{
		offSet=GPlayerListDataType.off;
		list=new CreateDataFunc[GPlayerListDataType.count-offSet];
		list[GPlayerListDataType.GPlayer-offSet]=this::createGPlayerListData;
	}
	
	private BaseData createGPlayerListData()
	{
		return new GPlayerListData();
	}
	
}
