package com.home.base.tool.generate;
import com.home.base.constlist.generate.GPlayerListClientDataType;
import com.home.base.part.player.list.GPlayerClientListData;
import com.home.shine.data.BaseData;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class GPlayerListClientDataMaker extends DataMaker
{
	public GPlayerListClientDataMaker()
	{
		offSet=GPlayerListClientDataType.off;
		list=new CreateDataFunc[GPlayerListClientDataType.count-offSet];
		list[GPlayerListClientDataType.GPlayer-offSet]=this::createGPlayerClientListData;
	}
	
	private BaseData createGPlayerClientListData()
	{
		return new GPlayerClientListData();
	}
	
}
