package com.home.base.tool.generate;
import com.home.base.constlist.generate.HotfixDataType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class HotfixDataMaker extends DataMaker
{
	public HotfixDataMaker()
	{
		offSet=HotfixDataType.off;
		list=new CreateDataFunc[HotfixDataType.count-offSet];
	}
	
}
