package com.home.base.tool.generate;
import com.home.base.constlist.generate.HPlayerPartClientDataType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class HPlayerPartClientDataMaker extends DataMaker
{
	public HPlayerPartClientDataMaker()
	{
		offSet=HPlayerPartClientDataType.off;
		list=new CreateDataFunc[HPlayerPartClientDataType.count-offSet];
	}
	
}
