package com.home.base.tool.generate;
import com.home.base.constlist.generate.HPlayerPartDataType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class HPlayerPartDataMaker extends DataMaker
{
	public HPlayerPartDataMaker()
	{
		offSet=HPlayerPartDataType.off;
		list=new CreateDataFunc[HPlayerPartDataType.count-offSet];
	}
	
}
