package com.home.base.tool.generate;
import com.home.base.constlist.generate.HPlayerListClientDataType;
import com.home.base.part.hPlayer.list.HPlayerClientListData;
import com.home.shine.data.BaseData;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class HPlayerListClientDataMaker extends DataMaker
{
	public HPlayerListClientDataMaker()
	{
		offSet=HPlayerListClientDataType.off;
		list=new CreateDataFunc[HPlayerListClientDataType.count-offSet];
		list[HPlayerListClientDataType.HPlayer-offSet]=this::createHPlayerClientListData;
	}
	
	private BaseData createHPlayerClientListData()
	{
		return new HPlayerClientListData();
	}
	
}
