package com.home.base.tool.generate;
import com.home.base.constlist.generate.HPlayerListDataType;
import com.home.base.part.hPlayer.list.HPlayerListData;
import com.home.shine.data.BaseData;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class HPlayerListDataMaker extends DataMaker
{
	public HPlayerListDataMaker()
	{
		offSet=HPlayerListDataType.off;
		list=new CreateDataFunc[HPlayerListDataType.count-offSet];
		list[HPlayerListDataType.HPlayer-offSet]=this::createHPlayerListData;
	}
	
	private BaseData createHPlayerListData()
	{
		return new HPlayerListData();
	}
	
}
