package com.home.manager.constlist.generate;

/** (generated by shine) */
public class GManagerHttpResponseType
{
	/** 起始 */
	public static final int off=11005;
	
	/** 计数 */
	public static final int count=11005;
	
}
