using ShineEngine;

/// <summary>
/// 玩家数据主体(generated by shine)
/// </summary>
public class GPlayer:Player
{
	/// <summary>
	/// 角色
	/// </summary>
	public GRolePart grole;
	
	/// <summary>
	/// 角色
	/// </summary>
	public GCharacterPart gcharacter;
	
	/// <summary>
	/// 背包
	/// </summary>
	public GBagPart gbag;
	
	/// <summary>
	/// 工会
	/// </summary>
	public GUnionPart gunion;
	
	/// <summary>
	/// 功能
	/// </summary>
	public GFuncPart gfunc;
	
	/// <summary>
	/// 好友
	/// </summary>
	public GFriendPart gfriend;
	
	/// <summary>
	/// 组队
	/// </summary>
	public GTeamPart gteam;
	
	/// <summary>
	/// 场景
	/// </summary>
	public GScenePart gscene;
	
	/// <summary>
	/// 注册部件
	/// </summary>
	protected override void registParts()
	{
		_list=new PlayerBasePart[14];
		int i=0;
		
		system=new SystemPart();
		system.setMe(this);
		_list[i++]=system;
		
		gfunc=new GFuncPart();
		func=gfunc;
		gfunc.setMe(this);
		_list[i++]=gfunc;
		
		activity=new ActivityPart();
		activity.setMe(this);
		_list[i++]=activity;
		
		grole=new GRolePart();
		role=grole;
		grole.setMe(this);
		_list[i++]=grole;
		
		gscene=new GScenePart();
		scene=gscene;
		gscene.setMe(this);
		_list[i++]=gscene;
		
		gcharacter=new GCharacterPart();
		character=gcharacter;
		gcharacter.setMe(this);
		_list[i++]=gcharacter;
		
		social=new SocialPart();
		social.setMe(this);
		_list[i++]=social;
		
		gbag=new GBagPart();
		bag=gbag;
		gbag.setMe(this);
		_list[i++]=gbag;
		
		mail=new MailPart();
		mail.setMe(this);
		_list[i++]=mail;
		
		quest=new QuestPart();
		quest.setMe(this);
		_list[i++]=quest;
		
		guide=new GuidePart();
		guide.setMe(this);
		_list[i++]=guide;
		
		gfriend=new GFriendPart();
		friend=gfriend;
		gfriend.setMe(this);
		_list[i++]=gfriend;
		
		gunion=new GUnionPart();
		union=gunion;
		gunion.setMe(this);
		_list[i++]=gunion;
		
		gteam=new GTeamPart();
		team=gteam;
		gteam.setMe(this);
		_list[i++]=gteam;
		
	}
	
	/// <summary>
	/// 创建列表数据
	/// </summary>
	public override PlayerListData createListData()
	{
		return new GPlayerListData();
	}
	
	/// <summary>
	/// 从列表数据读取
	/// </summary>
	public override void readListData(PlayerListData listData)
	{
		GPlayerListData mData=(GPlayerListData)listData;
		
		this.system.setData(mData.system);
		this.gfunc.setData(mData.gfunc);
		this.activity.setData(mData.activity);
		this.grole.setData(mData.grole);
		this.gscene.setData(mData.gscene);
		this.gcharacter.setData(mData.gcharacter);
		this.social.setData(mData.social);
		this.gbag.setData(mData.gbag);
		this.mail.setData(mData.mail);
		this.quest.setData(mData.quest);
		this.guide.setData(mData.guide);
		this.gfriend.setData(mData.gfriend);
		this.gunion.setData(mData.gunion);
		this.gteam.setData(mData.gteam);
	}
	
	/// <summary>
	/// 写列表数据(深拷)
	/// </summary>
	public override void writeListData(PlayerListData listData)
	{
		GPlayerListData mData=(GPlayerListData)listData;
		
		mData.system=(SystemPartData)this.system.makePartData();
		mData.gfunc=(GFuncPartData)this.gfunc.makePartData();
		mData.activity=(ActivityPartData)this.activity.makePartData();
		mData.grole=(GRolePartData)this.grole.makePartData();
		mData.gscene=(GScenePartData)this.gscene.makePartData();
		mData.gcharacter=(GCharacterPartData)this.gcharacter.makePartData();
		mData.social=(SocialPartData)this.social.makePartData();
		mData.gbag=(GBagPartData)this.gbag.makePartData();
		mData.mail=(MailPartData)this.mail.makePartData();
		mData.quest=(QuestPartData)this.quest.makePartData();
		mData.guide=(GuidePartData)this.guide.makePartData();
		mData.gfriend=(GFriendPartData)this.gfriend.makePartData();
		mData.gunion=(GUnionPartData)this.gunion.makePartData();
		mData.gteam=(GTeamPartData)this.gteam.makePartData();
	}
	
}
