package com.home.base.config.game;
import com.home.commonBase.config.game.FunctionConfig;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.support.collection.IntObjectMap;

/** 功能表(generated by shine) */
public class GFunctionConfig extends FunctionConfig
{
	/** 存储集合 */
	private static IntObjectMap<GFunctionConfig> _dic;
	
	/** 开关ID */
	public int switchID;
	
	/** 获取 */
	public static GFunctionConfig getG(int id)
	{
		return _dic.get(id);
	}
	
	/** 设置字典 */
	public static void setGDic(IntObjectMap<GFunctionConfig> dic)
	{
		_dic=dic;
	}
	
	/** 获取全部 */
	public static IntObjectMap<GFunctionConfig> getGDic()
	{
		return _dic;
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.switchID=stream.readShort();
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeShort(this.switchID);
		
	}
	
	/** 读完所有表后处理 */
	public static void afterReadConfigAll()
	{
		
	}
	
}
