package com.home.sceneBase.constlist.generate;

/** (generated by shine) */
public class GSceneBaseRequestType
{
	/** 起始 */
	public static final int off=9005;
	
	/** 计数 */
	public static final int count=9006;
	
	public static final int UnitChangeShootDir=9005;
	
}
