package com.home.sceneBase.constlist.generate;

/** (generated by shine) */
public class GSceneBaseResponseType
{
	/** 起始 */
	public static final int off=9305;
	
	/** 计数 */
	public static final int count=9306;
	
	/** 控制单位改变设计朝向消息 */
	public static final int CUnitChangeShootDir=9305;
	
}
