package com.home.sceneBase.constlist.generate;

/** (generated by shine) */
public class HSceneBaseResponseType
{
	/** 起始 */
	public static final int off=16512;
	
	/** 计数 */
	public static final int count=16512;
	
}
