package com.home.sceneBase.constlist.generate;

/** (generated by shine) */
public class HSceneBaseRequestType
{
	/** 起始 */
	public static final int off=16312;
	
	/** 计数 */
	public static final int count=16312;
	
}
