package com.home.base.data.login;
import com.home.base.constlist.generate.GBaseDataType;
import com.home.commonBase.data.login.GameLoginData;
import com.home.commonBase.data.social.rank.PlayerRankData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.collection.SList;

/** g层游戏服登录数据(generated by shine) */
public class GGameLoginData extends GameLoginData
{
	/** 数据类型ID */
	public static final int dataID=GBaseDataType.GGameLogin;
	
	/** 下个赛季时间 */
	public long nextSeasonTime;
	
	/** 上赛季排行榜 */
	public SList<PlayerRankData> lastSeasonRank;
	
	public GGameLoginData()
	{
		_dataID=GBaseDataType.GGameLogin;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "GGameLoginData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.endWriteObj();
	}
	
}
