package com.home.scene.constlist.generate;

/** (generated by shine) */
public class GSceneRequestType
{
	/** 起始 */
	public static final int off=9605;
	
	/** 计数 */
	public static final int count=9605;
	
}
