package com.home.scene.constlist.generate;

/** (generated by shine) */
public class GSceneResponseType
{
	/** 起始 */
	public static final int off=9905;
	
	/** 计数 */
	public static final int count=9905;
	
}
