package com.home.scene.constlist.generate;

/** (generated by shine) */
public class HGameSceneResponseType
{
	/** 起始 */
	public static final int off=15412;
	
	/** 计数 */
	public static final int count=15412;
	
}
