package com.home.scene.constlist.generate;

/** (generated by shine) */
public class HGameSceneRequestType
{
	/** 起始 */
	public static final int off=14912;
	
	/** 计数 */
	public static final int count=14912;
	
}
