package com.home.scene.constlist.generate;

/** (generated by shine) */
public class HSceneRequestType
{
	/** 起始 */
	public static final int off=16712;
	
	/** 计数 */
	public static final int count=16712;
	
}
