package com.home.scene.constlist.generate;

/** (generated by shine) */
public class HSceneResponseType
{
	/** 起始 */
	public static final int off=16912;
	
	/** 计数 */
	public static final int count=16912;
	
}
