package com.home.game.constlist.generate;

/** (generated by shine) */
public class GGameResponseType
{
	/** 起始 */
	public static final int off=8005;
	
	/** 计数 */
	public static final int count=8006;
	
}
