package com.home.game.constlist.generate;

/** (generated by shine) */
public class GGameRequestType
{
	/** 起始 */
	public static final int off=7005;
	
	/** 计数 */
	public static final int count=7006;
	
}
