package com.home.game.constlist.generate;

/** (generated by shine) */
public class HGameRequestType
{
	/** 起始 */
	public static final int off=15312;
	
	/** 计数 */
	public static final int count=15312;
	
}
