package com.home.game.constlist.generate;

/** (generated by shine) */
public class HGameResponseType
{
	/** 起始 */
	public static final int off=15812;
	
	/** 计数 */
	public static final int count=15812;
	
}
