package com.home.login.constlist.generate;

/** (generated by shine) */
public class GLoginHttpResponseResultType
{
	/** 起始 */
	public static final int off=10605;
	
	/** 计数 */
	public static final int count=10605;
	
}
