package com.home.game.tool.generate;
import com.home.game.constlist.generate.GGameRequestType;
import com.home.game.constlist.generate.GGameResponseType;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class GGameResponseBindTool extends MessageBindTool
{
	public GGameResponseBindTool()
	{
		offSet=GGameResponseType.off;
		list=new int[GGameResponseType.count-offSet][];
	}
	
}
