package com.home.game.tool.generate;
import com.home.base.constlist.generate.GServerMessageType;
import com.home.shine.data.BaseData;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class GGameServerResponseMaker extends DataMaker
{
	public GGameServerResponseMaker()
	{
		offSet=GServerMessageType.off;
		list=new CreateDataFunc[GServerMessageType.count-offSet];
	}
	
}
