package com.home.game.tool.generate;
import com.home.game.constlist.generate.HGameRequestType;
import com.home.game.constlist.generate.HGameResponseType;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class HGameResponseBindTool extends MessageBindTool
{
	public HGameResponseBindTool()
	{
		offSet=HGameResponseType.off;
		list=new int[HGameResponseType.count-offSet][];
	}
	
}
