package com.home.scene.tool.generate;
import com.home.scene.constlist.generate.GSceneRequestType;
import com.home.scene.constlist.generate.GSceneResponseType;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class GSceneResponseBindTool extends MessageBindTool
{
	public GSceneResponseBindTool()
	{
		offSet=GSceneResponseType.off;
		list=new int[GSceneResponseType.count-offSet][];
	}
	
}
