package com.home.scene.tool.generate;
import com.home.base.constlist.generate.GServerMessageType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class GSceneServerRequestMaker extends DataMaker
{
	public GSceneServerRequestMaker()
	{
		offSet=GServerMessageType.off;
		list=new CreateDataFunc[GServerMessageType.count-offSet];
	}
	
}
