package com.home.scene.tool.generate;
import com.home.scene.constlist.generate.HGameSceneRequestType;
import com.home.scene.constlist.generate.HGameSceneResponseType;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class HGameSceneResponseBindTool extends MessageBindTool
{
	public HGameSceneResponseBindTool()
	{
		offSet=HGameSceneResponseType.off;
		list=new int[HGameSceneResponseType.count-offSet][];
	}
	
}
