package com.home.scene.tool.generate;
import com.home.scene.constlist.generate.HGameSceneRequestType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class HGameSceneRequestMaker extends DataMaker
{
	public HGameSceneRequestMaker()
	{
		offSet=HGameSceneRequestType.off;
		list=new CreateDataFunc[HGameSceneRequestType.count-offSet];
	}
	
}
