package com.home.scene.tool.generate;
import com.home.scene.constlist.generate.HSceneRequestType;
import com.home.scene.constlist.generate.HSceneResponseType;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class HSceneResponseBindTool extends MessageBindTool
{
	public HSceneResponseBindTool()
	{
		offSet=HSceneResponseType.off;
		list=new int[HSceneResponseType.count-offSet][];
	}
	
}
