package com.home.base.constlist.generate;

/** 活动表(generated by shine) */
public class GActivityType
{
	/** 测试活动 */
	public static final int Test=101;
	
	/** 长度 */
	public static int size=0;
	
}
