package com.home.base.constlist.generate;

/** 属性类型表(generated by shine) */
public class GAttributeType
{
	/** 当前生命 */
	public static final int Hp=1;
	
	/** 生命上限 */
	public static final int HpMax=2;
	
	/** 当前魔法 */
	public static final int Mp=3;
	
	/** 魔法上限 */
	public static final int MpMax=4;
	
	/** 生命恢复速度 */
	public static final int HpRecover=5;
	
	/** 魔法恢复速度 */
	public static final int MpRecover=6;
	
	/** 攻击速度 */
	public static final int AttackSpeed=7;
	
	/** 施法速度 */
	public static final int CastSpeed=8;
	
	/** 移动速度 */
	public static final int MoveSpeed=9;
	
	/** 命中 */
	public static final int HitRate=10;
	
	/** 闪避 */
	public static final int Dodge=11;
	
	/** 暴击 */
	public static final int Crit=12;
	
	/** 韧性 */
	public static final int Tenacity=13;
	
	/** 物理攻击 */
	public static final int PhysicsAttack=14;
	
	/** 魔法攻击 */
	public static final int MagicAttack=15;
	
	/** 物理防御 */
	public static final int PhysicsDefence=16;
	
	/** 魔法防御 */
	public static final int MagicDefence=17;
	
	/** 物理破甲 */
	public static final int PhysicsReduce=18;
	
	/** 魔法破甲 */
	public static final int MagicReduce=19;
	
	/** 物理伤害盾 */
	public static final int PhysicsShield=20;
	
	/** 魔法伤害盾 */
	public static final int MagicShield=21;
	
	/** 物理伤害增加率 */
	public static final int PhysicsDamageAddPercent=22;
	
	/** 魔法伤害增加率 */
	public static final int MagicDamageAddPercent=23;
	
	/** 物理伤害减免率 */
	public static final int PhysicsDamageDeratePercent=24;
	
	/** 魔法伤害减免率 */
	public static final int MagicDamageDeratePercent=25;
	
	/** 总伤害减免率 */
	public static final int AllDemageDeratePercent=26;
	
	/** 伤害浮动比率 */
	public static final int DamageRandomRatio=27;
	
	/** 暴击伤害比率增加 */
	public static final int CritDamagePercentAdd=28;
	
	/** 治疗效果增加率 */
	public static final int HealAddPercent=29;
	
	/** 生命上限A */
	public static final int HpMaxA=101;
	
	/** 生命上限B */
	public static final int HpMaxB=102;
	
	/** 生命上限C */
	public static final int HpMaxC=103;
	
	/** 魔法上限A */
	public static final int MpMaxA=104;
	
	/** 魔法上限B */
	public static final int MpMaxB=105;
	
	/** 魔法上限C */
	public static final int MpMaxC=106;
	
	/** 攻击速度A */
	public static final int AttackSpeedA=107;
	
	/** 攻击速度B */
	public static final int AttackSpeedB=108;
	
	/** 攻击速度C */
	public static final int AttackSpeedC=109;
	
	/** 施法速度A */
	public static final int CastSpeedA=110;
	
	/** 施法速度B */
	public static final int CastSpeedB=111;
	
	/** 施法速度C */
	public static final int CastSpeedC=112;
	
	/** 移动速度A */
	public static final int MoveSpeedA=113;
	
	/** 移动速度B */
	public static final int MoveSpeedB=114;
	
	/** 移动速度C */
	public static final int MoveSpeedC=115;
	
	/** 命中A */
	public static final int HitRateA=116;
	
	/** 命中B */
	public static final int HitRateB=117;
	
	/** 命中C */
	public static final int HitRateC=118;
	
	/** 闪避A */
	public static final int DodgeA=119;
	
	/** 闪避B */
	public static final int DodgeB=120;
	
	/** 闪避C */
	public static final int DodgeC=121;
	
	/** 暴击A */
	public static final int CritA=122;
	
	/** 暴击B */
	public static final int CritB=123;
	
	/** 暴击C */
	public static final int CritC=124;
	
	/** 韧性A */
	public static final int TenacityA=125;
	
	/** 韧性B */
	public static final int TenacityB=126;
	
	/** 韧性C */
	public static final int TenacityC=127;
	
	/** 物理攻击A */
	public static final int PhysicsAttackA=128;
	
	/** 物理攻击B */
	public static final int PhysicsAttackB=129;
	
	/** 物理攻击C */
	public static final int PhysicsAttackC=130;
	
	/** 魔法攻击A */
	public static final int MagicAttackA=131;
	
	/** 魔法攻击B */
	public static final int MagicAttackB=132;
	
	/** 魔法攻击C */
	public static final int MagicAttackC=133;
	
	/** 物理防御A */
	public static final int PhysicsDefenceA=134;
	
	/** 物理防御B */
	public static final int PhysicsDefenceB=135;
	
	/** 物理防御C */
	public static final int PhysicsDefenceC=136;
	
	/** 魔法防御A */
	public static final int MagicDefenceA=137;
	
	/** 魔法防御B */
	public static final int MagicDefenceB=138;
	
	/** 魔法防御C */
	public static final int MagicDefenceC=139;
	
	/** 物理破甲A */
	public static final int PhysicsReduceA=140;
	
	/** 物理破甲B */
	public static final int PhysicsReduceB=141;
	
	/** 物理破甲C */
	public static final int PhysicsReduceC=142;
	
	/** 魔法破甲A */
	public static final int MagicReduceA=143;
	
	/** 魔法破甲B */
	public static final int MagicReduceB=144;
	
	/** 魔法破甲C */
	public static final int MagicReduceC=145;
	
	/** 长度 */
	public static int size=146;
	
}
