package com.home.base.constlist.generate;

/** (generated by shine) */
public class GBaseDataType
{
	/** 起始 */
	public static final int off=5605;
	
	/** 计数 */
	public static final int count=5613;
	
	/** 主角身份数据 */
	public static final int GCharacterIdentity=5605;
	
	/** 角色存库信息(跟CharacterCacheDO没有关系) */
	public static final int GCharacterSave=5606;
	
	/** 游戏角色使用数据 */
	public static final int GCharacterUse=5607;
	
	/** g层游戏服登录数据 */
	public static final int GGameLogin=5608;
	
	/** 角色外显数据 */
	public static final int GRoleShow=5609;
	
	/** 工会数据 */
	public static final int GUnion=5610;
	
	/** g层工会简版数据 */
	public static final int GUnionSimple=5611;
	
	/** g单位位置数据 */
	public static final int GUnitPos=5612;
	
}
