package com.home.base.constlist.generate;

/** (generated by shine) */
public class GBaseTableType
{
	/** 起始 */
	public static final int off=50;
	
	/** 计数 */
	public static final int count=51;
	
}
