package com.home.base.constlist.generate;

/** (generated by shine) */
public class GCenterGlobalPartDataType
{
	/** 起始 */
	public static final int off=12205;
	
	/** 计数 */
	public static final int count=12208;
	
	public static final int GCenterUnion=12205;
	
	public static final int GCenterFunc=12207;
	
}
