package com.home.base.constlist.generate;

/** (generated by shine) */
public class GCenterPlayerListDataType
{
	/** 起始 */
	public static final int off=12406;
	
	/** 计数 */
	public static final int count=12407;
	
	public static final int GCenterPlayer=12406;
	
}
