package com.home.base.constlist.generate;

/** (generated by shine) */
public class GCenterGlobalListDataType
{
	/** 起始 */
	public static final int off=12305;
	
	/** 计数 */
	public static final int count=12306;
	
	/** 中心服列表数据 */
	public static final int GCenterGlobal=12305;
	
}
