package com.home.base.constlist.generate;

/** (generated by shine) */
public class GCenterPlayerPartDataType
{
	/** 起始 */
	public static final int off=12306;
	
	/** 计数 */
	public static final int count=12306;
	
}
