package com.home.base.constlist.generate;

/** (generated by shine) */
public class GConfigType
{
	/** 起始 */
	public static final int off=501;
	
	/** 计数 */
	public static final int count=502;
	
	/** 道具表 */
	public static final int CustomF=501;
	
}
