package com.home.base.constlist.generate;

/** 装备槽位类型(generated by shine) */
public class GEquipSlotType
{
	/** 武器位 */
	public static final int Weapon=1;
	
	/** 上衣位 */
	public static final int Coat=2;
	
	/** 长度 */
	public static int size=3;
	
}
