package com.home.base.constlist.generate;

/** 功能表(generated by shine) */
public class GFunctionType
{
	/** 大乱斗 */
	public static final int Melee=101;
	
	/** 长度 */
	public static int size=0;
	
}
