package com.home.base.constlist.generate;

/** (generated by shine) */
public class GGameGlobalPartDataType
{
	/** 起始 */
	public static final int off=12407;
	
	/** 计数 */
	public static final int count=12410;
	
	public static final int GGameFunc=12407;
	
	public static final int GGameUnion=12408;
	
	public static final int GGameTeam=12409;
	
}
