package com.home.base.constlist.generate;

/** (generated by shine) */
public class GGameGlobalListDataType
{
	/** 起始 */
	public static final int off=12507;
	
	/** 计数 */
	public static final int count=12508;
	
	public static final int GGameGlobal=12507;
	
}
