package com.home.base.constlist.generate;

/** 道具装备类型(generated by shine) */
public class GItemEquipType
{
	/** 武器 */
	public static final int Weapon=1;
	
	/** 上衣 */
	public static final int Coat=2;
	
	/** 长度 */
	public static int size=3;
	
}
