package com.home.base.constlist.generate;

/** 地图格子阻挡类型类型(generated by shine) */
public class GMapBlockType
{
	/** 可通过 */
	public static final int Enable=0;
	
	/** 墙(不可通过) */
	public static final int Wall=11;
	
	/** 石头墙(可击碎) */
	public static final int Stone=12;
	
	/** 长度 */
	public static int size=13;
	
}
