package com.home.base.constlist.generate;

/** (generated by shine) */
public class GPlayerListClientDataType
{
	/** 起始 */
	public static final int off=12909;
	
	/** 计数 */
	public static final int count=12910;
	
	/** 玩家数据主体 */
	public static final int GPlayer=12909;
	
}
