package com.home.base.constlist.generate;

/** (generated by shine) */
public class GPlayerPartDataType
{
	/** 起始 */
	public static final int off=12508;
	
	/** 计数 */
	public static final int count=12516;
	
	/** 背包 */
	public static final int GBag=12508;
	
	/** 角色模块 */
	public static final int GCharacter=12509;
	
	public static final int GRole=12510;
	
	public static final int GUnion=12511;
	
	public static final int GFriend=12512;
	
	public static final int GFunc=12513;
	
	public static final int GTeam=12514;
	
	public static final int GScene=12515;
	
}
