package com.home.base.constlist.generate;

/** (generated by shine) */
public class GPlayerPartClientDataType
{
	/** 起始 */
	public static final int off=12708;
	
	/** 计数 */
	public static final int count=12716;
	
	public static final int GBag=12708;
	
	/** 角色模块 */
	public static final int GCharacter=12709;
	
	public static final int GRole=12710;
	
	public static final int GUnion=12711;
	
	public static final int GFriend=12712;
	
	public static final int GFunc=12713;
	
	public static final int GTeam=12714;
	
	public static final int GScene=12715;
	
}
