package com.home.base.constlist.generate;

/** (generated by shine) */
public class GPlayerListDataType
{
	/** 起始 */
	public static final int off=12908;
	
	/** 计数 */
	public static final int count=12909;
	
	/** 玩家数据主体 */
	public static final int GPlayer=12908;
	
}
