package com.home.base.constlist.generate;

/** 机器人测试模式(generated by shine) */
public class GRobotTestModeType
{
	/** 场景内随机找点移动 */
	public static final int RandomMove=7;
	
	/** 测试gm指令 */
	public static final int TestGM=101;
	
	/** 测试大乱斗 */
	public static final int TestMelee=102;
	
	/** 长度 */
	public static int size=103;
	
}
