package com.home.base.constlist.generate;

/** 玩家群职位表(generated by shine) */
public class GRoleGroupTitleType
{
	/** 群主 */
	public static final int Leader=1;
	
	/** 普通成员 */
	public static final int Member=2;
	
	/** 长度 */
	public static int size=3;
	
}
