package com.home.base.constlist.generate;

/** 玩家群数据变更类型(generated by shine) */
public class GRoleGroupChangeType
{
	/** 得分 */
	public static final int Score=101;
	
	/** 亮值 */
	public static final int Nice=102;
	
	/** 长度 */
	public static int size=103;
	
}
