package com.home.base.constlist.generate;

/** 场景类型(generated by shine) */
public class GSceneType
{
	/** 大乱斗场景 */
	public static final int Melee=1;
	
	/** 大乱斗单人场景 */
	public static final int MeleeSingle=2;
	
	/** 大乱斗帧同步场景 */
	public static final int MeleeFrameSync=3;
	
	/** 测试场景 */
	public static final int Test=9;
	
	/** 长度 */
	public static int size=10;
	
}
