package com.home.base.constlist.generate;

/** (generated by shine) */
public class GServerMessageType
{
	/** 起始 */
	public static final int off=11205;
	
	/** 计数 */
	public static final int count=11207;
	
}
