package com.home.base.constlist.generate;

/** 队伍目标表(generated by shine) */
public class GTeamTargetType
{
	/** 关卡1 */
	public static final int Battle1=1;
	
	/** 长度 */
	public static int size=2;
	
}
