package com.home.base.constlist.generate;

/** (generated by shine) */
public class GTriggerFunctionType
{
	/** 起始 */
	public static final int off=1000;
	
	/** 计数 */
	public static final int count=1001;
	
	public static final int GTestFunc=1000;
	
}
