package com.home.base.constlist.generate;

/** (generated by shine) */
public class GTriggerEventType
{
	/** 起始 */
	public static final int off=1000;
	
	/** 计数 */
	public static final int count=1000;
	
}
