package com.home.base.constlist.generate;

/** (generated by shine) */
public class GTriggerGroupType
{
	/** 起始 */
	public static final int off=20;
	
	/** 计数 */
	public static final int count=20;
	
}
