package com.home.base.constlist.generate;

/** (generated by shine) */
public class GTriggerObjectType
{
	/** 起始 */
	public static final int off=70;
	
	/** 计数 */
	public static final int count=70;
	
}
