package com.home.base.constlist.generate;

/** 单位AI指令类型(generated by shine) */
public class GUnitAICommandType
{
	/** 乱走 */
	public static final int Chaos=101;
	
	/** 长度 */
	public static int size=102;
	
}
