package com.home.base.constlist.generate;

/** 职业表(generated by shine) */
public class GVocationType
{
	/** 战士(默认职业) */
	public static final int Warrior=1;
	
	/** 长度 */
	public static int size=2;
	
}
