package com.home.base.constlist.generate;

/** (generated by shine) */
public class HConfigType
{
	/** 起始 */
	public static final int off=1001;
	
	/** 计数 */
	public static final int count=1001;
	
}
