package com.home.base.constlist.generate;

/** (generated by shine) */
public class HotfixDataType
{
	/** 起始 */
	public static final int off=6605;
	
	/** 计数 */
	public static final int count=6605;
	
}
