package com.home.base.constlist.generate;

/** (generated by shine) */
public class HPlayerListDataType
{
	/** 起始 */
	public static final int off=13310;
	
	/** 计数 */
	public static final int count=13311;
	
	/** 热更角色数据 */
	public static final int HPlayer=13310;
	
}
