package com.home.base.constlist.generate;

/** (generated by shine) */
public class HPlayerPartClientDataType
{
	/** 起始 */
	public static final int off=13110;
	
	/** 计数 */
	public static final int count=13110;
	
}
