package com.home.base.constlist.generate;

/** (generated by shine) */
public class HPlayerListClientDataType
{
	/** 起始 */
	public static final int off=13311;
	
	/** 计数 */
	public static final int count=13312;
	
	/** 热更角色数据 */
	public static final int HPlayer=13311;
	
}
