package com.home.base.constlist.generate;

/** (generated by shine) */
public class HPlayerPartDataType
{
	/** 起始 */
	public static final int off=12910;
	
	/** 计数 */
	public static final int count=12910;
	
}
