package com.home.base.constlist.generate;
import com.home.commonBase.config.game.TextConfig;

/** 程序文本枚举(generated by shine) */
public class HTextEnum
{
	/** 从配置读取 */
	public static void readConfig()
	{
		
	}
	
}
