using ShineEngine;

/// <summary>
/// 活动表(generated by shine)
/// </summary>
public class GActivityType
{
	/// <summary>
	/// 测试活动
	/// </summary>
	public const int Test=101;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=0;
	
}
