using ShineEngine;

/// <summary>
/// 属性类型表(generated by shine)
/// </summary>
public class GAttributeType
{
	/// <summary>
	/// 当前生命
	/// </summary>
	public const int Hp=1;
	
	/// <summary>
	/// 生命上限
	/// </summary>
	public const int HpMax=2;
	
	/// <summary>
	/// 当前魔法
	/// </summary>
	public const int Mp=3;
	
	/// <summary>
	/// 魔法上限
	/// </summary>
	public const int MpMax=4;
	
	/// <summary>
	/// 生命恢复速度
	/// </summary>
	public const int HpRecover=5;
	
	/// <summary>
	/// 魔法恢复速度
	/// </summary>
	public const int MpRecover=6;
	
	/// <summary>
	/// 攻击速度
	/// </summary>
	public const int AttackSpeed=7;
	
	/// <summary>
	/// 施法速度
	/// </summary>
	public const int CastSpeed=8;
	
	/// <summary>
	/// 移动速度
	/// </summary>
	public const int MoveSpeed=9;
	
	/// <summary>
	/// 命中
	/// </summary>
	public const int HitRate=10;
	
	/// <summary>
	/// 闪避
	/// </summary>
	public const int Dodge=11;
	
	/// <summary>
	/// 暴击
	/// </summary>
	public const int Crit=12;
	
	/// <summary>
	/// 韧性
	/// </summary>
	public const int Tenacity=13;
	
	/// <summary>
	/// 物理攻击
	/// </summary>
	public const int PhysicsAttack=14;
	
	/// <summary>
	/// 魔法攻击
	/// </summary>
	public const int MagicAttack=15;
	
	/// <summary>
	/// 物理防御
	/// </summary>
	public const int PhysicsDefence=16;
	
	/// <summary>
	/// 魔法防御
	/// </summary>
	public const int MagicDefence=17;
	
	/// <summary>
	/// 物理破甲
	/// </summary>
	public const int PhysicsReduce=18;
	
	/// <summary>
	/// 魔法破甲
	/// </summary>
	public const int MagicReduce=19;
	
	/// <summary>
	/// 物理伤害盾
	/// </summary>
	public const int PhysicsShield=20;
	
	/// <summary>
	/// 魔法伤害盾
	/// </summary>
	public const int MagicShield=21;
	
	/// <summary>
	/// 物理伤害增加率
	/// </summary>
	public const int PhysicsDamageAddPercent=22;
	
	/// <summary>
	/// 魔法伤害增加率
	/// </summary>
	public const int MagicDamageAddPercent=23;
	
	/// <summary>
	/// 物理伤害减免率
	/// </summary>
	public const int PhysicsDamageDeratePercent=24;
	
	/// <summary>
	/// 魔法伤害减免率
	/// </summary>
	public const int MagicDamageDeratePercent=25;
	
	/// <summary>
	/// 总伤害减免率
	/// </summary>
	public const int AllDemageDeratePercent=26;
	
	/// <summary>
	/// 伤害浮动比率
	/// </summary>
	public const int DamageRandomRatio=27;
	
	/// <summary>
	/// 暴击伤害比率增加
	/// </summary>
	public const int CritDamagePercentAdd=28;
	
	/// <summary>
	/// 治疗效果增加率
	/// </summary>
	public const int HealAddPercent=29;
	
	/// <summary>
	/// 生命上限A
	/// </summary>
	public const int HpMaxA=101;
	
	/// <summary>
	/// 生命上限B
	/// </summary>
	public const int HpMaxB=102;
	
	/// <summary>
	/// 生命上限C
	/// </summary>
	public const int HpMaxC=103;
	
	/// <summary>
	/// 魔法上限A
	/// </summary>
	public const int MpMaxA=104;
	
	/// <summary>
	/// 魔法上限B
	/// </summary>
	public const int MpMaxB=105;
	
	/// <summary>
	/// 魔法上限C
	/// </summary>
	public const int MpMaxC=106;
	
	/// <summary>
	/// 攻击速度A
	/// </summary>
	public const int AttackSpeedA=107;
	
	/// <summary>
	/// 攻击速度B
	/// </summary>
	public const int AttackSpeedB=108;
	
	/// <summary>
	/// 攻击速度C
	/// </summary>
	public const int AttackSpeedC=109;
	
	/// <summary>
	/// 施法速度A
	/// </summary>
	public const int CastSpeedA=110;
	
	/// <summary>
	/// 施法速度B
	/// </summary>
	public const int CastSpeedB=111;
	
	/// <summary>
	/// 施法速度C
	/// </summary>
	public const int CastSpeedC=112;
	
	/// <summary>
	/// 移动速度A
	/// </summary>
	public const int MoveSpeedA=113;
	
	/// <summary>
	/// 移动速度B
	/// </summary>
	public const int MoveSpeedB=114;
	
	/// <summary>
	/// 移动速度C
	/// </summary>
	public const int MoveSpeedC=115;
	
	/// <summary>
	/// 命中A
	/// </summary>
	public const int HitRateA=116;
	
	/// <summary>
	/// 命中B
	/// </summary>
	public const int HitRateB=117;
	
	/// <summary>
	/// 命中C
	/// </summary>
	public const int HitRateC=118;
	
	/// <summary>
	/// 闪避A
	/// </summary>
	public const int DodgeA=119;
	
	/// <summary>
	/// 闪避B
	/// </summary>
	public const int DodgeB=120;
	
	/// <summary>
	/// 闪避C
	/// </summary>
	public const int DodgeC=121;
	
	/// <summary>
	/// 暴击A
	/// </summary>
	public const int CritA=122;
	
	/// <summary>
	/// 暴击B
	/// </summary>
	public const int CritB=123;
	
	/// <summary>
	/// 暴击C
	/// </summary>
	public const int CritC=124;
	
	/// <summary>
	/// 韧性A
	/// </summary>
	public const int TenacityA=125;
	
	/// <summary>
	/// 韧性B
	/// </summary>
	public const int TenacityB=126;
	
	/// <summary>
	/// 韧性C
	/// </summary>
	public const int TenacityC=127;
	
	/// <summary>
	/// 物理攻击A
	/// </summary>
	public const int PhysicsAttackA=128;
	
	/// <summary>
	/// 物理攻击B
	/// </summary>
	public const int PhysicsAttackB=129;
	
	/// <summary>
	/// 物理攻击C
	/// </summary>
	public const int PhysicsAttackC=130;
	
	/// <summary>
	/// 魔法攻击A
	/// </summary>
	public const int MagicAttackA=131;
	
	/// <summary>
	/// 魔法攻击B
	/// </summary>
	public const int MagicAttackB=132;
	
	/// <summary>
	/// 魔法攻击C
	/// </summary>
	public const int MagicAttackC=133;
	
	/// <summary>
	/// 物理防御A
	/// </summary>
	public const int PhysicsDefenceA=134;
	
	/// <summary>
	/// 物理防御B
	/// </summary>
	public const int PhysicsDefenceB=135;
	
	/// <summary>
	/// 物理防御C
	/// </summary>
	public const int PhysicsDefenceC=136;
	
	/// <summary>
	/// 魔法防御A
	/// </summary>
	public const int MagicDefenceA=137;
	
	/// <summary>
	/// 魔法防御B
	/// </summary>
	public const int MagicDefenceB=138;
	
	/// <summary>
	/// 魔法防御C
	/// </summary>
	public const int MagicDefenceC=139;
	
	/// <summary>
	/// 物理破甲A
	/// </summary>
	public const int PhysicsReduceA=140;
	
	/// <summary>
	/// 物理破甲B
	/// </summary>
	public const int PhysicsReduceB=141;
	
	/// <summary>
	/// 物理破甲C
	/// </summary>
	public const int PhysicsReduceC=142;
	
	/// <summary>
	/// 魔法破甲A
	/// </summary>
	public const int MagicReduceA=143;
	
	/// <summary>
	/// 魔法破甲B
	/// </summary>
	public const int MagicReduceB=144;
	
	/// <summary>
	/// 魔法破甲C
	/// </summary>
	public const int MagicReduceC=145;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=146;
	
}
