using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GBaseDataType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=5605;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=5613;
	
	/// <summary>
	/// 主角身份数据
	/// </summary>
	public const int GCharacterIdentity=5605;
	
	/// <summary>
	/// 角色存库信息(跟CharacterCacheDO没有关系)
	/// </summary>
	public const int GCharacterSave=5606;
	
	/// <summary>
	/// 游戏角色使用数据
	/// </summary>
	public const int GCharacterUse=5607;
	
	/// <summary>
	/// g层游戏服登录数据
	/// </summary>
	public const int GGameLogin=5608;
	
	/// <summary>
	/// 角色外显数据
	/// </summary>
	public const int GRoleShow=5609;
	
	/// <summary>
	/// 工会数据
	/// </summary>
	public const int GUnion=5610;
	
	/// <summary>
	/// g层工会简版数据
	/// </summary>
	public const int GUnionSimple=5611;
	
	/// <summary>
	/// g单位位置数据
	/// </summary>
	public const int GUnitPos=5612;
	
}
