using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GCenterResponseType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=10205;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=10205;
	
}
