using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GCenterRequestType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=10405;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=10405;
	
}
