using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GConfigType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=501;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=502;
	
	/// <summary>
	/// 道具表
	/// </summary>
	public const int CustomF=501;
	
}
