using ShineEngine;

/// <summary>
/// 装备槽位类型(generated by shine)
/// </summary>
public class GEquipSlotType
{
	/// <summary>
	/// 武器位
	/// </summary>
	public const int Weapon=1;
	
	/// <summary>
	/// 上衣位
	/// </summary>
	public const int Coat=2;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=3;
	
}
