using ShineEngine;

/// <summary>
/// 功能表(generated by shine)
/// </summary>
public class GFunctionType
{
	/// <summary>
	/// 大乱斗
	/// </summary>
	public const int Melee=101;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=0;
	
}
