using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GGameResponseType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=7005;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=7006;
	
}
