using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GGameRequestType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=8005;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=8006;
	
}
