using ShineEngine;

/// <summary>
/// 道具装备类型(generated by shine)
/// </summary>
public class GItemEquipType
{
	/// <summary>
	/// 武器
	/// </summary>
	public const int Weapon=1;
	
	/// <summary>
	/// 上衣
	/// </summary>
	public const int Coat=2;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=3;
	
}
