using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GLoginHttpRequestType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=10705;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=10705;
	
}
