using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GLoginHttpResponseResultType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=10605;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=10605;
	
}
