using ShineEngine;

/// <summary>
/// 地图格子阻挡类型类型(generated by shine)
/// </summary>
public class GMapBlockType
{
	/// <summary>
	/// 可通过
	/// </summary>
	public const int Enable=0;
	
	/// <summary>
	/// 墙(不可通过)
	/// </summary>
	public const int Wall=11;
	
	/// <summary>
	/// 石头墙(可击碎)
	/// </summary>
	public const int Stone=12;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=13;
	
}
