using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GPlayerPartDataType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=12708;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=12716;
	
	public const int GBag=12708;
	
	/// <summary>
	/// 角色模块
	/// </summary>
	public const int GCharacter=12709;
	
	public const int GRole=12710;
	
	public const int GUnion=12711;
	
	public const int GFriend=12712;
	
	public const int GFunc=12713;
	
	public const int GTeam=12714;
	
	public const int GScene=12715;
	
}
