using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GPlayerListDataType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=12909;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=12910;
	
	/// <summary>
	/// 玩家数据主体
	/// </summary>
	public const int GPlayer=12909;
	
}
