using ShineEngine;

/// <summary>
/// 玩家群数据变更类型(generated by shine)
/// </summary>
public class GRoleGroupChangeType
{
	/// <summary>
	/// 得分
	/// </summary>
	public const int Score=101;
	
	/// <summary>
	/// 亮值
	/// </summary>
	public const int Nice=102;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=103;
	
}
