using ShineEngine;

/// <summary>
/// 玩家群职位表(generated by shine)
/// </summary>
public class GRoleGroupTitleType
{
	/// <summary>
	/// 群主
	/// </summary>
	public const int Leader=1;
	
	/// <summary>
	/// 普通成员
	/// </summary>
	public const int Member=2;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=3;
	
}
