using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GSceneRequestType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=9905;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=9905;
	
}
