using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GSceneBaseRequestType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=9305;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=9306;
	
	/// <summary>
	/// 控制单位改变设计朝向消息
	/// </summary>
	public const int CUnitChangeShootDir=9305;
	
}
