using ShineEngine;

/// <summary>
/// 场景类型(generated by shine)
/// </summary>
public class GSceneType
{
	/// <summary>
	/// 大乱斗场景
	/// </summary>
	public const int Melee=1;
	
	/// <summary>
	/// 大乱斗单人场景
	/// </summary>
	public const int MeleeSingle=2;
	
	/// <summary>
	/// 大乱斗帧同步场景
	/// </summary>
	public const int MeleeFrameSync=3;
	
	/// <summary>
	/// 测试场景
	/// </summary>
	public const int Test=9;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=10;
	
}
