using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GSceneResponseType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=9605;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=9605;
	
}
