using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GSceneBaseResponseType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=9005;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=9006;
	
	public const int UnitChangeShootDir=9005;
	
}
