using ShineEngine;

/// <summary>
/// 队伍目标表(generated by shine)
/// </summary>
public class GTeamTargetType
{
	/// <summary>
	/// 关卡1
	/// </summary>
	public const int Battle1=1;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=2;
	
}
