using ShineEngine;

/// <summary>
/// 程序文本枚举(generated by shine)
/// </summary>
public class GTextEnum
{
	/// <summary>
	/// 通用文本
	/// </summary>
	public static string Ok;
	
	/// <summary>
	/// 通用文本
	/// </summary>
	public static string Cancel;
	
	/// <summary>
	/// 从配置读取
	/// </summary>
	public static void readConfig()
	{
		Ok=TextConfig.getText("ok");
		Cancel=TextConfig.getText("cancel");
	}
	
}
