using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GTriggerGroupType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=20;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=20;
	
}
