using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GTriggerFunctionType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=1000;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=1001;
	
	public const int GTestFunc=1000;
	
}
