using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GTriggerEventType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=1000;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=1000;
	
}
