using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class GTriggerObjectType
{
	/// <summary>
	/// 起始
	/// </summary>
	public const int off=70;
	
	/// <summary>
	/// 计数
	/// </summary>
	public const int count=70;
	
}
