using ShineEngine;

/// <summary>
/// 单位AI指令类型(generated by shine)
/// </summary>
public class GUnitAICommandType
{
	/// <summary>
	/// 乱走
	/// </summary>
	public const int Chaos=101;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=102;
	
}
