using ShineEngine;

/// <summary>
/// 职业表(generated by shine)
/// </summary>
public class GVocationType
{
	/// <summary>
	/// 战士(默认职业)
	/// </summary>
	public const int Warrior=1;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=2;
	
}
