package com.home.sceneBase.tool.generate;
import com.home.sceneBase.constlist.generate.GSceneBaseRequestType;
import com.home.sceneBase.constlist.generate.GSceneBaseResponseType;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class GSceneBaseResponseBindTool extends MessageBindTool
{
	public GSceneBaseResponseBindTool()
	{
		offSet=GSceneBaseResponseType.off;
		list=new int[GSceneBaseResponseType.count-offSet][];
	}
	
}
