package com.home.sceneBase.tool.generate;
import com.home.sceneBase.constlist.generate.HSceneBaseRequestType;
import com.home.sceneBase.constlist.generate.HSceneBaseResponseType;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class HSceneBaseResponseBindTool extends MessageBindTool
{
	public HSceneBaseResponseBindTool()
	{
		offSet=HSceneBaseResponseType.off;
		list=new int[HSceneBaseResponseType.count-offSet][];
	}
	
}
