package com.home.base.global;
import com.home.commonBase.global.GlobalReadData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.data.DIntData;

/** 全局配置表(generated by shine) */
public class GGlobalReadData extends GlobalReadData
{
	/** 默认角色职业 */
	public int defaultVocation;
	
	/** 大乱斗人数 */
	public int meleePlayerNum;
	
	/** 大乱斗匹配最长等待时间(s) */
	public int meleeMatchMaxTime;
	
	/** 乱走AI半径(米) */
	public float chaosMoveRadius;
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.defaultVocation=stream.readInt();
		
		this.meleePlayerNum=stream.readInt();
		
		this.meleeMatchMaxTime=stream.readInt();
		
		this.chaosMoveRadius=stream.readFloat();
		
	}
	
}
