package com.home.base.global;
import com.home.base.global.GGlobalReadData;
import com.home.shine.data.DIntData;

/** 全局配置表(generated by shine) */
public class GGlobal
{
	/** 默认角色职业 */
	public static int defaultVocation;
	
	/** 大乱斗人数 */
	public static int meleePlayerNum;
	
	/** 大乱斗匹配最长等待时间(s) */
	public static int meleeMatchMaxTime;
	
	/** 乱走AI半径(米) */
	public static float chaosMoveRadius;
	
	/** 从流读取 */
	public static void readFromData(GGlobalReadData data)
	{
		defaultVocation=data.defaultVocation;
		meleePlayerNum=data.meleePlayerNum;
		meleeMatchMaxTime=data.meleeMatchMaxTime;
		chaosMoveRadius=data.chaosMoveRadius;
	}
	
	/** 读取数据后 */
	public static void afterReadConfig()
	{
	
	}
	
	/** 全部读取后 */
	public static void afterReadConfigAll()
	{
		
	}
	
}
