package com.home.base.global;
import com.home.base.global.HGlobalReadData;

/** 全局配置表(generated by shine) */
public class HGlobal
{
	/** 从流读取 */
	public static void readFromData(HGlobalReadData data)
	{
		
	}
	
	/** 读取数据后 */
	public static void afterReadConfig()
	{
	
	}
	
	/** 全部读取后 */
	public static void afterReadConfigAll()
	{
		
	}
	
}
