package com.home.base.global;
import com.home.base.global.GGlobalReadData;
import com.home.shine.bytes.BytesReadStream;

/** 全局配置表(generated by shine) */
public class HGlobalReadData extends GGlobalReadData
{
}
