package com.home.base.data.scene.unit;
import com.home.base.constlist.generate.GBaseDataType;
import com.home.commonBase.data.scene.unit.identity.CharacterIdentityData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;

/** 主角身份数据(generated by shine) */
public class GCharacterIdentityData extends CharacterIdentityData
{
	/** 数据类型ID */
	public static final int dataID=GBaseDataType.GCharacterIdentity;
	
	public GCharacterIdentityData()
	{
		_dataID=GBaseDataType.GCharacterIdentity;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "GCharacterIdentityData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.endWriteObj();
	}
	
}
