package com.home.game.control;

import com.home.commonGame.control.PlayerWorkControl;

/** 游戏角色事务控制(generated by shine) */
public class GPlayerWorkControl extends PlayerWorkControl
{
	/** 注册 */
	@Override
	public void regist()
	{
		super.regist();
		
	}
	
	
}
