using ShineEngine;

/// <summary>
/// 本地存储类型(generated by shine)
/// </summary>
public class GLocalSaveType
{
	/// <summary>
	/// 操作方式
	/// </summary>
	public const int Hand=1000;
	
	/// <summary>
	/// 已经进入主界面
	/// </summary>
	public const int IsAlreadyInMain=1001;
	
	/// <summary>
	/// 已经打开魔盒
	/// </summary>
	public const int IsAlreadyOpenBox=1002;
	
	/// <summary>
	/// 已经打开角色
	/// </summary>
	public const int IsAlreadyOpenCharacter=1003;

}
