using ShineEngine;
using UnityEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class UIElement_joystick:UIElement
{
	public UIObject rect;
	
	public UIImage chassis;
	
	public UIImage thumb;
	
	public override void init(GameObject obj)
	{
		base.init(obj);
		
		ElementInfo[] exports=obj.transform.GetComponent<UIElementComponent>().exports;
		
		rect=new UIObject();
		rect.name="rect";
		rect.init(exports[0].obj);
		registChild(rect);
		
		chassis=new UIImage();
		chassis.name="chassis";
		chassis.init(exports[1].obj);
		registChild(chassis);
		
		thumb=new UIImage();
		thumb.name="thumb";
		thumb.init(exports[2].obj);
		registChild(thumb);
		
	}
	
}
