using ShineEngine;
using UnityEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class UIElement_InitLoading:UIElement
{
	public override void init(GameObject obj)
	{
		base.init(obj);
		
		ElementInfo[] exports=obj.transform.GetComponent<UIElementComponent>().exports;
		
	}
	
}
