package com.home.client.constlist.generate;

/** (generated by shine) */
public class GCenterResponseType
{
	/** 起始 */
	public static final int off=10205;
	
	/** 计数 */
	public static final int count=10205;
	
}
