package com.home.client.constlist.generate;

/** (generated by shine) */
public class GCenterRequestType
{
	/** 起始 */
	public static final int off=10405;
	
	/** 计数 */
	public static final int count=10405;
	
}
