package com.home.client.constlist.generate;

/** (generated by shine) */
public class GGameResponseType
{
	/** 起始 */
	public static final int off=7005;
	
	/** 计数 */
	public static final int count=7006;
	
}
