package com.home.client.constlist.generate;

/** (generated by shine) */
public class GGameRequestType
{
	/** 起始 */
	public static final int off=8005;
	
	/** 计数 */
	public static final int count=8006;
	
}
