package com.home.client.constlist.generate;

/** (generated by shine) */
public class GLoginHttpRequestType
{
	/** 起始 */
	public static final int off=10705;
	
	/** 计数 */
	public static final int count=10705;
	
}
