package com.home.client.constlist.generate;

/** (generated by shine) */
public class GSceneResponseType
{
	/** 起始 */
	public static final int off=9605;
	
	/** 计数 */
	public static final int count=9605;
	
}
