package com.home.client.constlist.generate;

/** (generated by shine) */
public class GSceneRequestType
{
	/** 起始 */
	public static final int off=9905;
	
	/** 计数 */
	public static final int count=9905;
	
}
