package com.home.client.constlist.generate;

/** (generated by shine) */
public class HGameRequestType
{
	/** 起始 */
	public static final int off=15812;
	
	/** 计数 */
	public static final int count=15812;
	
}
