package com.home.client.constlist.generate;

/** (generated by shine) */
public class HGameResponseType
{
	/** 起始 */
	public static final int off=15312;
	
	/** 计数 */
	public static final int count=15312;
	
}
