package com.home.client.constlist.generate;

/** (generated by shine) */
public class HSceneRequestType
{
	/** 起始 */
	public static final int off=16912;
	
	/** 计数 */
	public static final int count=16912;
	
}
