package com.home.client.constlist.generate;

/** (generated by shine) */
public class HSceneResponseType
{
	/** 起始 */
	public static final int off=16712;
	
	/** 计数 */
	public static final int count=16712;
	
}
