package com.home.base.part.player.clientData;
import com.home.base.constlist.generate.GPlayerPartClientDataType;
import com.home.commonBase.part.player.clientData.FriendClientPartData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;

/** (generated by shine) */
public class GFriendClientPartData extends FriendClientPartData
{
	/** 数据类型ID */
	public static final int dataID=GPlayerPartClientDataType.GFriend;
	
	public GFriendClientPartData()
	{
		_dataID=GPlayerPartClientDataType.GFriend;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "GFriendClientPartData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.endWriteObj();
	}
	
	/** 从服务器数据上复制数据(潜拷,因InitClient会copy) */
	@Override
	protected void toCopyFromServer(BaseData data)
	{
		super.toCopyFromServer(data);
		
	}
	
}
