package com.home.client.tool.generate;
import com.home.client.constlist.generate.GCenterRequestType;
import com.home.client.constlist.generate.GCenterResponseType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class GCenterRequestBindTool extends MessageBindTool
{
	public GCenterRequestBindTool()
	{
		offSet=GCenterRequestType.off;
		list=new int[GCenterRequestType.count-offSet][];
	}
	
}
