package com.home.client.tool.generate;
import com.home.client.constlist.generate.GGameRequestType;
import com.home.client.constlist.generate.GGameResponseType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class GGameRequestBindTool extends MessageBindTool
{
	public GGameRequestBindTool()
	{
		offSet=GGameRequestType.off;
		list=new int[GGameRequestType.count-offSet][];
	}
	
}
