package com.home.client.tool.generate;
import com.home.client.constlist.generate.GSceneBaseResponseType;
import com.home.client.net.sceneBaseResponse.unit.UnitChangeShootDirResponse;
import com.home.shine.data.BaseData;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class GSceneBaseResponseMaker extends DataMaker
{
	public GSceneBaseResponseMaker()
	{
		offSet=GSceneBaseResponseType.off;
		list=new CreateDataFunc[GSceneBaseResponseType.count-offSet];
		list[GSceneBaseResponseType.UnitChangeShootDir-offSet]=this::createUnitChangeShootDirResponse;
	}
	
	private BaseData createUnitChangeShootDirResponse()
	{
		return new UnitChangeShootDirResponse();
	}
	
}
