package com.home.client.tool.generate;
import com.home.client.constlist.generate.GSceneRequestType;
import com.home.client.constlist.generate.GSceneResponseType;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class GSceneRequestBindTool extends MessageBindTool
{
	public GSceneRequestBindTool()
	{
		offSet=GSceneRequestType.off;
		list=new int[GSceneRequestType.count-offSet][];
	}
	
}
