package com.home.client.tool.generate;
import com.home.client.constlist.generate.GSceneBaseRequestType;
import com.home.client.constlist.generate.GSceneBaseResponseType;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class GSceneBaseRequestBindTool extends MessageBindTool
{
	public GSceneBaseRequestBindTool()
	{
		offSet=GSceneBaseRequestType.off;
		list=new int[GSceneBaseRequestType.count-offSet][];
	}
	
}
