package com.home.client.tool.generate;
import com.home.client.constlist.generate.GSceneResponseType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class GSceneResponseMaker extends DataMaker
{
	public GSceneResponseMaker()
	{
		offSet=GSceneResponseType.off;
		list=new CreateDataFunc[GSceneResponseType.count-offSet];
	}
	
}
