package com.home.client.tool.generate;
import com.home.client.constlist.generate.GSceneBaseRequestType;
import com.home.client.net.sceneBaseRequest.unit.CUnitChangeShootDirRequest;
import com.home.shine.data.BaseData;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class GSceneBaseRequestMaker extends DataMaker
{
	public GSceneBaseRequestMaker()
	{
		offSet=GSceneBaseRequestType.off;
		list=new CreateDataFunc[GSceneBaseRequestType.count-offSet];
		list[GSceneBaseRequestType.CUnitChangeShootDir-offSet]=this::createCUnitChangeShootDirRequest;
	}
	
	private BaseData createCUnitChangeShootDirRequest()
	{
		return new CUnitChangeShootDirRequest();
	}
	
}
