package com.home.client.tool.generate;
import com.home.client.constlist.generate.HCenterRequestType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class HCenterRequestMaker extends DataMaker
{
	public HCenterRequestMaker()
	{
		offSet=HCenterRequestType.off;
		list=new CreateDataFunc[HCenterRequestType.count-offSet];
	}
	
}
