package com.home.client.tool.generate;
import com.home.client.constlist.generate.HCenterResponseType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class HCenterResponseMaker extends DataMaker
{
	public HCenterResponseMaker()
	{
		offSet=HCenterResponseType.off;
		list=new CreateDataFunc[HCenterResponseType.count-offSet];
	}
	
}
