package com.home.client.tool.generate;
import com.home.client.constlist.generate.HCenterRequestType;
import com.home.client.constlist.generate.HCenterResponseType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class HCenterRequestBindTool extends MessageBindTool
{
	public HCenterRequestBindTool()
	{
		offSet=HCenterRequestType.off;
		list=new int[HCenterRequestType.count-offSet][];
	}
	
}
