package com.home.client.tool.generate;
import com.home.client.constlist.generate.HGameRequestType;
import com.home.client.constlist.generate.HGameResponseType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class HGameRequestBindTool extends MessageBindTool
{
	public HGameRequestBindTool()
	{
		offSet=HGameRequestType.off;
		list=new int[HGameRequestType.count-offSet][];
	}
	
}
