package com.home.client.tool.generate;
import com.home.client.constlist.generate.HGameResponseType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class HGameResponseMaker extends DataMaker
{
	public HGameResponseMaker()
	{
		offSet=HGameResponseType.off;
		list=new CreateDataFunc[HGameResponseType.count-offSet];
	}
	
}
