package com.home.client.tool.generate;
import com.home.client.constlist.generate.HSceneRequestType;
import com.home.client.constlist.generate.HSceneResponseType;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class HSceneRequestBindTool extends MessageBindTool
{
	public HSceneRequestBindTool()
	{
		offSet=HSceneRequestType.off;
		list=new int[HSceneRequestType.count-offSet][];
	}
	
}
