package com.home.client.tool.generate;
import com.home.client.constlist.generate.HSceneBaseResponseType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class HSceneBaseResponseMaker extends DataMaker
{
	public HSceneBaseResponseMaker()
	{
		offSet=HSceneBaseResponseType.off;
		list=new CreateDataFunc[HSceneBaseResponseType.count-offSet];
	}
	
}
