package com.home.client.tool.generate;
import com.home.client.constlist.generate.HSceneBaseRequestType;
import com.home.client.constlist.generate.HSceneBaseResponseType;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class HSceneBaseRequestBindTool extends MessageBindTool
{
	public HSceneBaseRequestBindTool()
	{
		offSet=HSceneBaseRequestType.off;
		list=new int[HSceneBaseRequestType.count-offSet][];
	}
	
}
