package com.home.client.tool.generate;
import com.home.client.constlist.generate.HSceneResponseType;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class HSceneResponseMaker extends DataMaker
{
	public HSceneResponseMaker()
	{
		offSet=HSceneResponseType.off;
		list=new CreateDataFunc[HSceneResponseType.count-offSet];
	}
	
}
